// The Pulsefit homepage, rebuilt whole: the product name throughout, no user counts, no third-party logos,
// no stock testimonials. Every figure is sample data.
P.site = () => {
  const i = P.i
  const chk = `<span style="width:22px;height:22px;border-radius:50%;background:#E6F0FF;color:#0063F8;display:grid;place-items:center;flex:none">${i('check', 'width:13px;height:13px;stroke-width:2.6')}</span>`
  const eyebrow = (t, dark) => `<div style="display:inline-flex;align-items:center;gap:8px;height:30px;padding:0 14px;border-radius:15px;background:${dark ? 'rgba(255,255,255,.1)' : '#EEF4FF'};color:${dark ? '#CFE0FF' : '#0063F8'};font-size:13px;font-weight:600"><span style="width:6px;height:6px;border-radius:50%;background:#FFB800"></span>${t}</div>`
  const h2 = t => `<h2 style="font:600 44px/1.12 Poppins;letter-spacing:-.03em;margin:18px 0 0">${t}</h2>`
  const lead = t => `<p style="font-size:18px;line-height:1.6;color:#4B5163;margin:16px 0 0">${t}</p>`
  // product preview in the hero: the real lead dashboard, scaled down
  const preview = `<div style="width:1120px;height:640px;border-radius:20px;overflow:hidden;box-shadow:0 0 0 8px rgba(255,255,255,.08),0 50px 100px -30px rgba(0,10,40,.7);position:relative"><div style="transform:scale(.7778);transform-origin:0 0;width:1440px">${P.leadDash()}</div></div>`
  const feat = (ic, t, d) => `<div style="border-radius:20px;background:#fff;box-shadow:0 0 0 1px #E8EBF2;padding:26px"><span class="ico" style="width:44px;height:44px;border-radius:12px;background:#EEF4FF;color:#0063F8">${i(ic, 'width:20px;height:20px')}</span><div style="font:600 18px Poppins;letter-spacing:-.01em;margin-top:18px">${t}</div><div style="font-size:15px;line-height:1.6;color:#4B5163;margin-top:8px">${d}</div></div>`
  const step = (n, t, d, body) => `<div style="flex:1 1 0;min-width:0;border-radius:24px;background:#fff;box-shadow:0 0 0 1px #E8EBF2;padding:24px"><div style="height:190px;border-radius:16px;background:#F5F7FB;padding:20px;position:relative;overflow:hidden">${body}</div><div style="display:flex;align-items:center;gap:10px;margin-top:22px"><span style="width:28px;height:28px;border-radius:50%;background:#003A92;color:#fff;font-weight:700;font-size:13px;display:grid;place-items:center">${n}</span><span style="font:600 19px Poppins;letter-spacing:-.01em">${t}</span></div><div style="font-size:15px;line-height:1.6;color:#4B5163;margin-top:10px">${d}</div></div>`
  const bar = (w, c) => `<div style="height:10px;width:${w}%;border-radius:5px;background:${c || '#DDE3EF'};margin-bottom:12px"></div>`
  const price = (n, p, d, hl, items) => `<div style="flex:1;border-radius:24px;padding:30px;position:relative;${hl ? 'background:#003A92;color:#fff;box-shadow:0 30px 60px -30px rgba(0,40,120,.6)' : 'background:#fff;box-shadow:0 0 0 1px #E8EBF2'}">${hl ? '<span style="position:absolute;right:24px;top:26px;height:26px;padding:0 10px;border-radius:13px;background:#FFB800;color:#3A2A00;font-size:12px;font-weight:700;display:grid;place-items:center">Most chosen</span>' : ''}<div style="font:600 20px Poppins">${n}</div><div style="font-size:14px;margin-top:6px;opacity:.75">${d}</div><div style="margin-top:22px;display:flex;align-items:baseline;gap:6px"><span style="font:600 46px Poppins;letter-spacing:-.03em">$${p}</span><span style="opacity:.7">/ month</span></div><div style="margin-top:22px;height:48px;border-radius:12px;display:grid;place-items:center;font-weight:600;font-size:15px;${hl ? 'background:#fff;color:#003A92' : 'background:#0063F8;color:#fff'}">Start free trial</div><div style="margin-top:26px;display:flex;flex-direction:column;gap:14px;font-size:15px">${items.map(x => `<div style="display:flex;gap:10px;align-items:center">${hl ? `<span style="width:22px;height:22px;border-radius:50%;background:rgba(255,255,255,.14);display:grid;place-items:center">${i('check', 'width:13px;height:13px;stroke-width:2.6')}</span>` : chk}${x}</div>`).join('')}</div></div>`
  const faq = (q, a) => `<div style="border-radius:18px;background:#fff;box-shadow:0 0 0 1px #E8EBF2;padding:22px 26px"><div style="display:flex;align-items:center;justify-content:space-between;font-weight:600;font-size:17px">${q}<span style="width:32px;height:32px;border-radius:50%;background:#F3F5F9;display:grid;place-items:center;color:#4B5163">${i(a ? 'x' : 'plus', 'width:15px;height:15px')}</span></div>${a ? `<div style="margin-top:12px;color:#4B5163;font-size:15px;line-height:1.65;max-width:620px">${a}</div>` : ''}</div>`
  const wrap = 'width:1200px;margin:0 auto'
  return `<div class="u" style="width:1440px;background:#fff;font-size:15px">
  <section style="background:radial-gradient(900px 500px at 25% 0%,#0A63E8 0%,#003A92 55%,#001A4A 100%);color:#fff;padding:28px 0 0;overflow:hidden">
    <div style="${wrap};display:flex;align-items:center;height:64px;padding:0 10px 0 22px;border-radius:18px;background:rgba(255,255,255,.07);box-shadow:inset 0 0 0 1px rgba(255,255,255,.12)"><div class="brand" style="padding:0;color:#fff;font-size:21px"><span style="width:24px;height:26px;display:block">${P.mark('dark')}</span>Pulsefit</div><div style="display:flex;gap:34px;margin-left:60px;font-size:15px;color:#D6E3FF"><span style="color:#fff">Product</span><span>Pricing</span><span>Blog</span><span>Contact</span></div><span style="margin-left:auto;font-size:15px;color:#D6E3FF;margin-right:22px">Log in</span><span style="height:44px;padding:0 20px;border-radius:12px;background:#fff;color:#003A92;font-weight:600;display:grid;place-items:center">Book a demo</span></div>
    <div style="text-align:center;padding:96px 0 0">${eyebrow('Gym management software', 1)}
      <h1 style="font:600 72px/1.04 Poppins;letter-spacing:-.04em;margin:26px auto 0;max-width:960px">Manage, grow and elevate your fitness business.</h1>
      <p style="font-size:20px;line-height:1.6;color:#C9DAFF;max-width:680px;margin:24px auto 0">Leads, members, plans, equipment and staff in one place, with every follow-up on time.</p>
      <div style="display:flex;gap:12px;justify-content:center;margin-top:36px"><span style="height:54px;padding:0 26px;border-radius:14px;background:#FFB800;color:#2A1E00;font-weight:700;font-size:16px;display:grid;place-items:center">Start free trial</span><span style="height:54px;padding:0 26px;border-radius:14px;box-shadow:inset 0 0 0 1px rgba(255,255,255,.35);font-weight:600;font-size:16px;display:flex;align-items:center;gap:8px">Book a demo${i('arrowR', 'width:17px;height:17px')}</span></div>
      <div style="display:flex;justify-content:center;margin-top:72px">${preview}</div></div>
  </section>
  <section style="padding:120px 0 0"><div style="${wrap};text-align:center">${eyebrow('Features')}${h2('Every tool you need, in one place')}<div style="max-width:640px;margin:0 auto">${lead('Built around the daily work of a gym front desk: who to call, who to renew, what is due.')}</div></div>
    <div style="${wrap};display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:56px">${feat('target', 'Leads and follow-ups', 'Stale and missed leads surface each morning, each with the next step.')}${feat('users', 'Members', 'Renewals, attendance drops and frozen plans in one view.')}${feat('tag', 'Plans and billing', 'Durations, GST, pauses and discounts set once, applied every time.')}${feat('mail', 'Automated emails', 'Welcome, trial and renewal emails sent by triggers, not by hand.')}${feat('dumbbell', 'Equipment', 'Track machines, log repairs and see what is out of service.')}${feat('user', 'Staff', 'Roles, shifts and who owns each lead and member.')}</div></section>
  <section style="padding:120px 0 0"><div style="${wrap};display:grid;grid-template-columns:1fr 1.15fr;gap:72px;align-items:center">
    <div>${eyebrow('Lead to member')}${h2('From first visit to first bill, without retyping')}${lead('A lead\'s details carry into the member form. Pick a plan, see the total, convert.')}<div style="display:flex;flex-direction:column;gap:16px;margin-top:30px;font-size:16px">${['Follow-ups scheduled for you', 'Hot, warm and cold at a glance', 'Plan and billing in the same step'].map(x => `<div style="display:flex;gap:12px;align-items:center">${chk}${x}</div>`).join('')}</div></div>
    <div style="border-radius:28px;background:linear-gradient(160deg,#EEF4FF,#F7FAFF);box-shadow:inset 0 0 0 1px #DCE7FA;padding:40px;display:flex;justify-content:center;height:600px;overflow:hidden"><div style="transform:scale(.88);transform-origin:top center">${P.convertModal()}</div></div></div></section>
  <section style="padding:120px 0 0"><div style="${wrap};text-align:center">${eyebrow('How it works')}${h2('Up and running in a day')}</div>
    <div style="${wrap};display:flex;gap:20px;margin-top:56px">
      ${step(1, 'Import your data', 'Bring members, plans and staff across from your spreadsheets.', `<div style="font-weight:600;font-size:13px;margin-bottom:14px">Import · members.csv</div>${bar(100, '#0063F8')}<div style="display:flex;flex-direction:column;gap:9px;font-size:12.5px;color:#4B5163;margin-top:6px">${['Members · 791', 'Plans · 12', 'Staff · 9'].map(x => `<div style="display:flex;gap:8px;align-items:center">${chk}${x}</div>`).join('')}</div>`)}
      ${step(2, 'Set up your gym', 'Choose plans, pricing and reminders to match how you run.', `<div style="display:flex;flex-direction:column;gap:10px">${P.PLANS.slice(0, 3).map(p => `<div style="display:flex;align-items:center;gap:10px;background:#fff;border-radius:10px;padding:9px 12px;box-shadow:0 0 0 1px #E8EBF2;font-size:12.5px;white-space:nowrap">${P.tag(p[0], p[1], 1)}<b style="font-weight:600">${p[2]}</b><span style="margin-left:auto;color:#4B5163">₹${p[3].toLocaleString('en-IN')}</span></div>`).join('')}</div>`)}
      ${step(3, 'Follow the day', 'Start each morning with the leads and renewals that need you.', `<div style="transform:scale(.62);transform-origin:0 0;width:520px">${P.taskCard('missed', { hov: 0 })}</div>`)}
    </div></section>
  <section style="padding:120px 0 0"><div style="${wrap};text-align:center">${eyebrow('Pricing')}${h2('Simple pricing that grows with you')}<div style="max-width:560px;margin:0 auto">${lead('Every plan includes a 14-day free trial. Change or cancel at any time.')}</div></div>
    <div style="${wrap};display:flex;gap:20px;margin-top:56px;align-items:flex-start">${price('Starter', 99, 'For a single studio getting started', 0, ['Leads and follow-ups', 'Member records', 'Plans and billing', 'Email support'])}${price('Growth', 199, 'For busy gyms with a front desk team', 1, ['Everything in Starter', 'Automated emails', 'Attendance insights', 'Equipment and repairs', 'Priority support'])}${price('Scale', 299, 'For gyms with more than one branch', 0, ['Everything in Growth', 'Multi-branch reports', 'Staff roles and shifts', 'Onboarding call'])}</div></section>
  <section style="padding:120px 0 0"><div style="${wrap};display:grid;grid-template-columns:1fr 1.5fr;gap:72px">
    <div>${eyebrow('FAQ')}${h2('Questions you might be asking')}${lead('Still unsure? Book a 20-minute demo and we will walk you through it.')}</div>
    <div style="display:flex;flex-direction:column;gap:14px">${faq('How long does it take to get started?', 'Most gyms are running within a day. We help import your members, plans and staff from your current spreadsheets.')}${faq('Can I import data from my current system?')}${faq('Do members get emails from Pulsefit?')}${faq('Is there a contract or commitment?')}${faq('What kind of support do you offer?')}</div></div></section>
  <section style="padding:120px 0"><div style="${wrap};border-radius:32px;background:radial-gradient(700px 400px at 20% 0%,#0A63E8,#003A92 60%,#001A4A);color:#fff;padding:80px;text-align:center">
    <h2 style="font:600 48px/1.1 Poppins;letter-spacing:-.03em;margin:0 auto;max-width:760px">Stop chasing follow-ups. Start growing your gym.</h2>
    <p style="font-size:18px;color:#C9DAFF;margin:18px 0 0">14-day free trial. No card needed.</p>
    <div style="display:flex;gap:12px;justify-content:center;margin-top:34px"><span style="height:54px;padding:0 26px;border-radius:14px;background:#FFB800;color:#2A1E00;font-weight:700;font-size:16px;display:grid;place-items:center">Start free trial</span><span style="height:54px;padding:0 26px;border-radius:14px;box-shadow:inset 0 0 0 1px rgba(255,255,255,.35);font-weight:600;font-size:16px;display:grid;place-items:center">Book a demo</span></div></div></section>
  <footer style="background:#0B1330;color:#B7C3E0;padding:72px 0 40px"><div style="${wrap};display:grid;grid-template-columns:1.6fr 1fr 1fr 1fr;gap:40px">
    <div><div class="brand" style="padding:0;color:#fff;font-size:21px"><span style="width:24px;height:26px;display:block">${P.mark('dark')}</span>Pulsefit</div><p style="font-size:15px;line-height:1.6;margin:18px 0 0;max-width:300px">Gym management software for leads, members, plans and staff.</p></div>
    ${[['Product', ['Features', 'Pricing', 'Book a demo']], ['Company', ['About', 'Blog', 'Contact']], ['Support', ['Help centre', 'FAQ', 'Privacy']]].map(([h, ls]) => `<div><div style="color:#fff;font-weight:600;font-size:15px">${h}</div><div style="display:flex;flex-direction:column;gap:12px;margin-top:18px;font-size:15px">${ls.map(l => `<span>${l}</span>`).join('')}</div></div>`).join('')}</div>
    <div style="${wrap};border-top:1px solid rgba(255,255,255,.1);margin-top:56px;padding-top:26px;font-size:14px;display:flex"><span>© 2024 Pulsefit</span><span style="margin-left:auto">Terms · Privacy</span></div></footer>
  </div>`
}
