// Jaadu 2.0 components rebuilt as HTML from the Figma tokens (get_variable_defs).
// All data is sample data. Content faults found in the Figma frames are fixed here.
const T = {
  bg: '#00022b', tx: '#f1f6ff', sec: '#a7bce4', mut: '#3b567a', icon: '#4c6aa5', dis: '#1e3354',
  p500: '#5985ff', p400: '#2653cf', p300: '#183585', p700: '#5cb5ff', acc: '#4da3ff',
  green: '#45ffb5', red: '#ff5971', yel: '#ffbd67', cyan: '#00ffff', btc: '#f7931a',
  b10: 'rgba(255,255,255,.1)', inp: 'rgba(31,60,139,.1)', elev: 'rgba(0,85,209,.1)',
  comp: 'rgba(0,52,194,.15)', glass: 'rgba(1,6,54,.5)',
}
const ic = (d, s = 18, c = 'currentColor', w = 1.7) => `<svg width="${s}" height="${s}" viewBox="0 0 24 24" fill="none" stroke="${c}" stroke-width="${w}" stroke-linecap="round" stroke-linejoin="round">${d}</svg>`
const P = {
  dash: '<rect x="4" y="4" width="7" height="9" rx="1.5" fill="currentColor"/><rect x="13" y="4" width="7" height="5" rx="1.5" fill="currentColor"/><rect x="4" y="15" width="7" height="5" rx="1.5" fill="currentColor"/><rect x="13" y="11" width="7" height="9" rx="1.5" fill="currentColor"/>',
  chat: '<path d="M20 12a8 8 0 11-3-6.2M19 3v4M17 5h4"/>',
  book: '<rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 8h6M9 12h6"/>',
  bulb: '<path d="M9 18h6M10 21h4M12 3a6 6 0 00-3.5 10.9c.6.5 1 1.2 1 2.1h5c0-.9.4-1.6 1-2.1A6 6 0 0012 3z"/><path d="M12.5 6.5l-1.5 3h2l-1.5 3"/>',
  alarm: '<circle cx="12" cy="13" r="7"/><path d="M12 10v6M9 13h6M4 5l3-2M20 5l-3-2"/>',
  bell: '<path d="M6 16V11a6 6 0 1112 0v5l2 2H4zM10 21h4"/>',
  search: '<circle cx="11" cy="11" r="6"/><path d="M20 20l-4-4"/>',
  plus: '<path d="M12 5v14M5 12h14"/>',
  chev: '<path d="M6 9l6 6 6-6"/>',
  chevu: '<path d="M6 15l6-6 6 6"/>',
  x: '<path d="M6 6l12 12M18 6L6 18"/>',
  lib: '<path d="M5 4v16M10 4v16M15 6l4 14"/>',
  paper: '<path d="M4 18l5-6 4 3 7-9"/><path d="M4 21h16"/>',
  hist: '<path d="M4 12a8 8 0 108-8 8 8 0 00-6 2.7L4 9M4 4v5h5M12 8v4l3 2"/>',
  stats: '<path d="M4 17l5-5 3 3 6-7"/><circle cx="17" cy="16" r="3"/><path d="M19 18l2 2"/>',
  list: '<path d="M4 6h16M4 12h16M4 18h10"/><path d="M17 15l1.2 2.4 2.6.4-1.9 1.8.5 2.6-2.4-1.3-2.4 1.3.5-2.6-1.9-1.8 2.6-.4z"/>',
  mail: '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 7l9 6 9-6"/>',
  toast: '<rect x="4" y="5" width="16" height="12" rx="2"/><path d="M8 20h8"/>',
  edit: '<path d="M4 20h4L19 9a2.8 2.8 0 00-4-4L4 16z"/>',
  cal: '<rect x="4" y="5" width="16" height="15" rx="2"/><path d="M4 10h16M9 3v4M15 3v4"/>',
  filter: '<path d="M4 8h9M17 8h3M4 16h3M11 16h9"/><circle cx="15" cy="8" r="2"/><circle cx="9" cy="16" r="2"/>',
  spin: '<path d="M12 3a9 9 0 109 9" /><path d="M12 7a5 5 0 105 5"/>',
  check: '<path d="M5 12l4 4 10-10"/>',
  steps: '<path d="M4 7h4M4 12h10M4 17h14"/><path d="M4 4v6"/>',
  star: '<path d="M12 3l2.6 5.6 6 .7-4.5 4.1 1.2 6L12 16.5 6.7 19.4l1.2-6L3.4 9.3l6-.7z"/>',
}
const I = (k, s, c, w) => ic(P[k], s, c, w)

const cardBg = `background:var(--cardbg,#08123C);border:1px solid var(--cardbd,rgba(255,255,255,.1));backdrop-filter:var(--cardbf,none)`
const flat = `background:var(--cardbg,#08123C);border:1px solid var(--cardbd,rgba(255,255,255,.1));backdrop-filter:var(--cardbf,none)`

const btcCoin = (s = 30) => `<div style="width:${s}px;height:${s}px;border-radius:50%;background:${T.btc};display:grid;place-items:center;color:#fff;font:700 ${s * .58}px Geist">₿</div>`

// ---- cards ----
const coinStats = () => `<div style="${cardBg};width:350px;height:331px;border-radius:24px;box-sizing:border-box;padding:20px 16px;display:flex;flex-direction:column;gap:12px;font-family:Geist">
 <div style="display:flex;justify-content:space-between;align-items:flex-start"><div style="display:flex;gap:12px">${btcCoin(30)}<div><div style="font:700 18px/20px Geist;color:${T.tx}">BTC</div><div style="font:500 10px/16px Geist;color:${T.sec}">Bitcoin / US Dollars</div></div></div>
 <div style="background:rgba(69,255,181,.1);border-radius:7px;padding:4px 8px;font:500 12px/20px Geist;color:${T.green}">+2.14%</div></div>
 <div style="height:1px;background:linear-gradient(90deg,rgba(255,255,255,0),rgba(255,255,255,.35),rgba(255,255,255,0))"></div>
 <div style="padding:0 4px"><div style="font:400 12px/20px Geist;color:${T.sec}">MARK PRICE</div><div style="color:${T.tx};font:700 24px/28px Geist">$60,553<span style="font:400 16px Geist;color:${T.sec}">.20</span></div></div>
 <div style="display:flex;gap:8px">${['INDEX PRICE|60,551.85', 'OPEN INTEREST|14,208 BTC'].map(x => { const [a, b] = x.split('|'); return `<div style="flex:1;background:${T.elev};border:.5px solid ${T.b10};border-radius:10px;padding:8px 12px"><div style="font:400 10px/12px Geist;color:${T.sec}">${a}</div><div style="font:500 12px/16px Geist;color:${T.tx};margin-top:8px">${b}</div></div>` }).join('')}</div>
 <div style="background:${T.elev};border:.5px solid ${T.b10};border-radius:10px;padding:8px 12px;height:50px;box-sizing:border-box;display:flex;justify-content:space-between;align-items:center"><span style="font:400 10px Geist;color:${T.sec}">24H VOLUME (USDT)</span><span style="font:500 12px Geist;color:${T.tx}">6,167,144,953.95</span></div>
 <div style="background:${T.elev};border:.5px solid ${T.b10};border-radius:10px;padding:8px 12px;display:flex;justify-content:space-between;align-items:center"><span style="font:400 10px Geist;color:${T.sec}">FUNDING (8H)</span><span style="text-align:right"><span style="font:500 12px Geist;color:${T.red}">▾ -0.00064%</span><br><span style="font:400 10px Geist;color:${T.sec}">Next in 00:54:02</span></span></div></div>`

const tradeRows = [['60,553.20', '0.352', '$21.3K', '19:15:44', 1], ['60,552.80', '0.118', '$7.1K', '19:15:43', 0], ['60,553.20', '0.640', '$38.8K', '19:15:41', 1], ['60,551.90', '0.205', '$12.4K', '19:15:39', 0], ['60,553.60', '0.091', '$5.5K', '19:15:38', 1], ['60,552.10', '0.477', '$28.9K', '19:15:36', 0], ['60,553.40', '0.263', '$15.9K', '19:15:34', 1], ['60,551.70', '0.152', '$9.2K', '19:15:31', 0]]
const trades = (n = 6, h = 212) => `<div style="${cardBg};width:360px;height:${h}px;border-radius:24px;box-sizing:border-box;padding:12px 16px;font-family:Geist;overflow:hidden">
 <div style="display:flex;justify-content:space-between;align-items:center;height:32px"><span style="font:600 14px Geist;color:${T.tx}">Trades</span><span style="color:${T.sec}">${I('filter', 18)}</span></div>
 <div style="display:grid;grid-template-columns:86px 86px 56px 1fr;font:500 10px Geist;color:${T.sec};margin:6px 0 8px"><span>Price</span><span>Size</span><span>Value</span><span style="text-align:right">Time</span></div>
 ${tradeRows.slice(0, n).map(r => `<div style="display:grid;grid-template-columns:86px 86px 56px 1fr;align-items:center;height:24px;font:500 12px 'IBM Plex Mono'"><span style="color:${r[4] ? T.green : T.red}">${r[0]}</span><span style="color:${T.sec};display:flex;align-items:center;gap:6px;font-weight:400">${r[1]}<i style="display:block;width:30px;height:3px;border-radius:8px;background:rgba(69,255,181,.1);position:relative"><b style="position:absolute;left:0;top:0;height:3px;border-radius:8px;width:${Math.round(parseFloat(r[1]) / .7 * 30)}px;background:${r[4] ? T.green : T.red}"></b></i></span><span style="color:${T.tx}">${r[2]}</span><span style="text-align:right;color:${T.mut}">${r[3]}</span></div>`).join('')}</div>`

const regime = (w = 912) => `<div style="${cardBg};width:${w}px;height:116px;border-radius:16px;box-sizing:border-box;padding:16px 18px;font-family:Geist">
 <div style="font:600 16px/22px Geist;color:#fff;margin:4px 0 8px">Regime</div>
 <div style="display:flex">${[['Sideways', 40, T.p500], ['Breakout', 35, T.red], ['Volatile', 13, T.yel], ['Reversal', 12, T.green]].map((s, i, a) => `<div style="width:${s[1]}%"><div style="height:30px;background:${s[2]};border-radius:${i == 0 ? '5px 0 0 5px' : i == 3 ? '0 5px 5px 0' : 0}"></div><div style="font:500 12px Geist;color:${T.sec};margin-top:2px">${s[0]}: ${s[1]}%</div></div>`).join('')}</div></div>`

const spark = (w, h, seed) => { const r = rng(seed); let y = h * .8, pts = []; for (let i = 0; i <= 24; i++) { y = Math.max(4, Math.min(h - 4, y - (r() - .38) * h * .14)); pts.push([i * w / 24, y]) } const d = pts.map((p, i) => (i ? 'L' : 'M') + p[0].toFixed(1) + ' ' + p[1].toFixed(1)).join(''); return `<svg width="${w}" height="${h}"><path d="${d}L${w} ${h}L0 ${h}Z" fill="rgba(69,255,181,.16)"/><path d="${d}" fill="none" stroke="${T.green}" stroke-width="2"/></svg>` }
const watchlist = () => `<div style="${cardBg};width:360px;height:160px;border-radius:24px;box-sizing:border-box;font-family:Geist;overflow:hidden;position:relative">
 <div style="display:flex;justify-content:space-between;padding:16px 16px 0;align-items:center"><span style="font:600 16px/22px Geist;color:${T.tx}">Watchlist</span><span style="color:${T.tx}">${I('plus', 24)}</span></div>
 <div style="display:flex;align-items:center;gap:8px;padding:12px 8px 0"><span style="width:24px;height:24px;border-radius:50%;background:${T.comp};display:grid;place-items:center;color:${T.sec}">${ic('<path d="M14 6l-6 6 6 6"/>', 16)}</span>
 <div style="flex:1;background:${T.elev};border:1px solid ${T.b10};border-radius:16px;padding:8px 12px;display:flex;justify-content:space-between;align-items:center"><div><div style="display:flex;gap:4px;align-items:center">${btcCoin(16)}<b style="font:600 14px Geist;color:${T.tx}">BTC</b></div><div style="font:500 14px/20px Geist;color:${T.tx}">$60,553.20</div><div style="font:400 12px 'IBM Plex Mono';color:${T.green}">+2.14%</div></div>${spark(96, 58, 7)}</div>
 <span style="width:24px;height:24px;border-radius:50%;background:${T.comp};display:grid;place-items:center;color:${T.sec}">${ic('<path d="M10 6l6 6-6 6"/>', 16)}</span></div>
 <div style="position:absolute;left:0;right:0;bottom:0;height:22px;background:${T.comp};border-top:.5px solid ${T.b10};display:grid;place-items:center;color:${T.tx}">${I('chev', 18)}</div></div>`

const quantSide = (h = 760) => `<div style="${cardBg};width:317px;height:${h}px;border-radius:16px;box-sizing:border-box;padding:0 16px;font-family:Geist;overflow:hidden;display:flex;flex-direction:column;gap:16px">
 <div style="border-bottom:1px solid rgba(128,197,255,.06);padding:20px 24px;display:flex;gap:8px;align-items:center;margin:0 -16px;color:${T.p700}">${I('bulb', 26, T.p700)}<span style="font:600 18px/24px Geist;color:${T.tx}">Quantlab</span></div>
 <div style="background:${T.p500};border:1px solid ${T.b10};border-radius:8px;padding:8px 12px;display:flex;gap:4px;justify-content:center;align-items:center;font:600 12px/16px Geist;color:${T.tx}">${I('plus', 16, T.tx)}New Lab Session</div>
 <div><div style="font:500 12px/16px Geist;color:${T.mut};margin-bottom:8px">Tools</div><div style="display:flex;flex-direction:column;gap:12px">
 ${[['bulb', 'Overnight Discoveries', 1], ['lib', 'Library', 0], ['paper', 'Paper Trade', 0], ['hist', 'Deja Vu', 0]].map(t => `<div style="height:40px;box-sizing:border-box;border-radius:8px;padding:8px 12px;display:flex;gap:8px;align-items:center;font:500 14px/20px Geist;${t[2] ? `background:${T.comp};border:.5px solid ${T.p300};color:${T.p700}` : `background:${T.glass};border:.5px solid ${T.b10};color:${T.tx}`}"><span style="color:${t[2] ? T.p700 : T.acc}">${I(t[0], 20)}</span>${t[1]}</div>`).join('')}</div></div>
 <div><div style="font:500 12px/16px Geist;color:${T.mut};margin-bottom:8px">History</div>${['Correlate BTC regime shifts..', 'Funding rate before 5%+drop..', 'Breakout start above VAH+..', 'Mean-reversion BTC', 'Correlate ETH regime shifts..', 'Funding rate before 5%+drop..', 'Mean-reversion SOL', 'Breakout start above VAH+..', 'Correlate BTC regime shifts..'].map((t, i) => `<div style="display:flex;gap:8px;align-items:center;padding:8px;font:500 14px/20px Geist;color:${T.sec}"><span style="color:${T.icon}">${I(i % 3 == 0 ? 'search' : i % 3 == 1 ? 'list' : 'hist', 18)}</span>${t}</div>`).join('')}</div></div>`

const campaign = () => `<div style="${cardBg};width:893px;height:259px;border-radius:16px;box-sizing:border-box;padding:18px 16px;font-family:Geist;display:flex;flex-direction:column;gap:17px">
 <div style="display:flex;gap:12px;align-items:center"><span style="color:${T.p700}">${ic('<circle cx="12" cy="12" r="9" opacity=".35"/><path d="M12 3a9 9 0 019 9"/><path d="M12 8a4 4 0 014 4"/>', 28, T.p700, 1.6)}</span><span style="font:500 14px/20px Geist;color:#fff">Campaign Running – 5 coins · Swing</span></div>
 <div style="display:flex;gap:4px;align-items:flex-end"><span style="font:700 28px/36px Geist;color:#fff">639</span><span style="font:400 14px/22px Geist;color:${T.sec}">candidates generated</span></div>
 <div style="height:8px;border-radius:8px;background:${T.inp};position:relative"><div style="width:58%;height:8px;border-radius:8px;background:linear-gradient(90deg,${T.p700},${T.p500} 30%,${T.p400} 63%,${T.p700});box-shadow:0 0 14px rgba(0,255,255,.35)"></div></div>
 <div style="display:flex;gap:12px">${[['Generated', 639, 'Evolutionary search'], ['Fast filter', 212, 'Stage 1 falsification'], ['Regime test', 57, 'Stage 2 falsification'], ['CPCV + PBO', 8, 'Stage 3 falsification']].map((s, i) => `<div style="flex:1;background:${T.glass};border:.5px solid ${T.b10};border-radius:8px;padding:12px"><div style="display:flex;gap:7px;align-items:center;font:400 14px/20px Geist;color:${T.sec}"><span style="width:24px;height:24px;border-radius:50%;border:2px solid ${T.p500};box-sizing:border-box;display:grid;place-items:center;font:600 11px Geist;color:${T.p700};opacity:${1 - i * .12}">${i + 1}</span>${s[0]}</div><div style="font:600 16px/22px Geist;color:#fff;margin-top:8px">${s[1]}</div><div style="font:400 12px/16px Geist;color:${T.sec}">${s[2]}</div></div>`).join('')}</div></div>`

const how = () => `<div style="width:730px;height:296px;font-family:Geist;display:flex;flex-direction:column;align-items:center;gap:28px;justify-content:center">
 <div style="text-align:center;width:423px;display:flex;flex-direction:column;align-items:center;gap:8px"><span style="color:${T.p700}">${I('bulb', 35, T.p700, 1.5)}</span>
 <div style="font:700 18px/24px Geist;color:${T.tx}"><span style="background:linear-gradient(90deg,#5cb5ff,#0ff);-webkit-background-clip:text;color:transparent">Automated strategy </span>research, run overnight.</div>
 <div style="font:400 12px/16px Geist;color:${T.sec}">Select your assets and timeframe. Jaadu searches and validates candidate strategies through the night and delivers a vetted shortlist by morning.</div></div>
 <div style="display:flex;gap:28px;padding:16px 0">${[['steps', 'You set it up', 'Pick at least 5 coins and a timeframe: Intra-day or Swing.'], ['stats', 'It works overnight', 'Jaadu generates thousands of candidate strategies.'], ['list', 'You wake up to a shortlist', 'By morning, only the strategies that survived every stage are ranked and ready to review.']].map((s, i) => `${i ? `<div style="width:1px;height:129px;background:linear-gradient(180deg,rgba(255,255,255,0),rgba(255,255,255,.5),rgba(255,255,255,0))"></div>` : ''}<div style="width:206px;display:flex;flex-direction:column;align-items:center;gap:12px"><div style="width:44px;height:44px;border-radius:8px;background:${T.glass};border:1px solid ${T.inp};display:grid;place-items:center;color:${T.p700}">${I(s[0], 26, T.p700)}</div><div style="text-align:center;color:${T.sec}"><div style="font:600 14px/20px Geist">${s[1]}</div><div style="font:400 10px/12px Geist;margin-top:2px">${s[2]}</div></div></div>`).join('')}</div></div>`

const libRows = [['MeanRev-VAL', T.red, '2.14', '+41.2%', '-12.6%', '58.4%', '1.74'], ['ReversalFade-4h', T.green, '1.82', '+33.7%', '-9.8%', '54.1%', '1.52'], ['FundingSkew-1h', T.p500, '1.47', '+26.9%', '-14.3%', '51.7%', '1.36'], ['TurboMOVE-vol', T.yel, '1.21', '+22.4%', '-17.9%', '47.9%', '1.28']]
const libTable = () => `<div style="${cardBg};width:891px;height:238px;border-radius:12px;box-sizing:border-box;padding:16px;font-family:Geist">
 <div style="font:500 14px/20px Geist;color:${T.tx};margin-bottom:12px">Comparison Table</div>
 <div style="display:grid;grid-template-columns:1fr 101px 102px 103px 101px 147px;font:500 10px/12px Geist;color:${T.mut};padding:5px 0;border-bottom:.5px solid ${T.dis};margin-bottom:8px"><span style="padding-left:10px">VARIANT</span><span style="padding-left:4px">SHARPE</span><span style="padding-left:4px">RETURN</span><span style="padding-left:4px">MAX DD</span><span style="padding-left:4px">WIN RATE</span><span style="text-align:right;padding-right:4px">PROFIT FACTOR</span></div>
 ${libRows.map((r, ri) => { const best = [0, 0, 1, 0, 0]; return `<div style="display:grid;grid-template-columns:1fr 101px 102px 103px 101px 147px;align-items:center;height:30px;margin-bottom:8px;font:500 12px Geist;color:${T.tx}"><span style="display:flex;gap:8px;align-items:center;font:500 14px Geist"><i style="width:8px;height:8px;border-radius:50%;background:${r[1]};display:block"></i>${r[0]}</span>${[2, 3, 4, 5, 6].map((c, ci) => { const hi = ri == (best[ci] ? 1 : 0); return `<span style="height:100%;display:flex;align-items:center;padding-left:${ci ? 4 : 12}px;${ci == 4 ? 'justify-content:flex-end;padding-right:4px;' : ''}${hi ? `background:${T.comp};` : ''}${ci < 2 ? `font-weight:600;color:${hi ? T.acc : T.tx}` : ''}">${r[c]}</span>` }).join('')}</div>` }).join('')}</div>`

const equity = () => { const r = rng(21); const cols = [T.red, T.green, T.p500, T.yel], fin = [41, 34, 27, 22]; const W = 840, H = 140; const lines = cols.map((c, k) => { let y = 0, pts = []; for (let i = 0; i <= 40; i++) { y += (fin[k] / 40) * (0.5 + r() * 1.0); pts.push([i * W / 40, H - 8 - y / 45 * (H - 20)]) } return `<path d="${pts.map((p, i) => (i ? 'L' : 'M') + p[0].toFixed(1) + ' ' + p[1].toFixed(1)).join('')}" fill="none" stroke="${c}" stroke-width="1.8"/>` }).join('')
  return `<div style="${cardBg};width:891px;height:280px;border-radius:12px;box-sizing:border-box;padding:19px 17px;font-family:Geist"><div style="font:500 14px/20px Geist;color:${T.tx}">Equity Curve</div><svg width="857" height="170" style="margin-top:16px">${[0, 1, 2, 3, 4, 5].map(i => `<line x1="0" x2="857" y1="${20 + i * 28}" y2="${20 + i * 28}" stroke="rgba(128,197,255,.1)"/>`).join('')}<g transform="translate(0,18)">${lines}</g></svg>
 <div style="display:flex;gap:12px;margin-top:14px;font:500 12px/20px Geist;color:${T.sec}">${libRows.map(r => `<span style="display:flex;gap:6px;align-items:center"><i style="width:8px;height:8px;border-radius:50%;background:${r[1]};display:block"></i>${r[0]}</span>`).join('')}</div></div>` }

const paramDiff = () => `<div style="${cardBg};width:891px;height:217px;border-radius:12px;box-sizing:border-box;padding:16px;font-family:Geist"><div style="font:500 14px/20px Geist;color:${T.tx}">Parameter-Diff View</div>
 <div style="display:grid;grid-template-columns:302px repeat(4,1fr);margin-top:16px;font-family:Geist">${[['PARAMETER', ['ENTRY STRUCTURE', 'FRAGILITY', 'TP/SL', 'REGIME GATE']], ['VAH-V3', ['Price > VAH', '0.50', '2.0/1.0', 'Breakout']], ['VAH-V2', ['Price > VAH', '0.55', '1.5/1.0', 'Breakout']], ['POC', ['Near POC', '0.50', '2.5/1.0', 'Breakout']], ['CVD', ['CVD slope', '0.45', '2.0/1.0', 'Breakout + vol']]].map((c, ci) => `<div><div style="font:500 10px/12px Geist;color:${T.mut};padding:8px 4px;border-bottom:.5px solid ${T.dis}">${c[0]}</div>${c[1].map(v => `<div style="height:26px;margin-top:4px;display:flex;align-items:center;padding:0 4px;font:${ci ? 500 : 500} ${ci ? 12 : 10}px Geist;color:${ci ? T.tx : T.mut};${ci && v == c[1][1] ? '' : ''}border-bottom:.5px solid rgba(255,255,255,.04)">${v}</div>`).join('')}</div>`).join('')}</div></div>`

const pill = (t, c, bg) => `<span style="display:inline-block;background:${bg};color:${c};border-radius:16px;padding:2px 16px;font:500 14px/20px Geist">${t}</span>`
const dot = (c, f) => `<span style="width:12px;height:12px;box-sizing:border-box;border-radius:6px;border:2px solid ${c};background:${f ? c : 'rgba(255,189,103,.1)'};display:grid;place-items:center">${f ? ic('<path d="M5 12l4 4 10-10"/>', 8, '#00022b', 4) : ''}</span>`
const alertCard = () => { const cond = [['Price', T.cyan, 'rgba(0,255,255,.1)', 'Above', T.p700, '$60,000', 'Candle 1h', 'now $60,553', 'MET', T.p500, 1, '27 Jul, 3:42'], ['POC', T.p700, T.comp, 'Below', T.red, '$60,800', 'Candle 1h', 'now $60,553', 'MET', T.p500, 1, '27 Jul, 3:42'], ['Footprint', T.yel, 'rgba(255,189,103,.1)', 'Enters', T.yel, '$60,600', 'Sustained 2h', '70% range · 1h', 'ACTIVE', T.green, 0, '–']]
  return `<div style="${flat};width:1182px;height:376px;border-radius:8px;box-sizing:border-box;padding:16px 20px;font-family:Geist;display:flex;flex-direction:column;gap:17px">
 <div style="position:relative;height:52px;width:1148px">
 <div style="position:absolute;left:0;top:5px"><div style="font:600 14px/20px Geist;color:${T.tx}">BTC/USDC</div><div style="font:400 12px/16px Geist;color:${T.sec};margin-top:5px">Bitcoin</div></div>
 <div style="position:absolute;left:129px;top:-1px;width:190px;display:flex;flex-wrap:wrap;gap:4px;zoom:.86">${pill('Footprint', T.yel, 'rgba(255,189,103,.1)')}${pill('Regime', T.p700, T.elev)}${pill('Volume', T.red, 'rgba(255,89,113,.1)')}${pill('+1', T.icon, T.inp)}</div>
 <div style="position:absolute;left:323px;top:2px"><span style="display:inline-flex;gap:6px;align-items:center;background:${T.inp};border:1px solid ${T.b10};border-radius:4px;padding:2px 8px;font:500 14px/20px Geist;color:${T.p700}">ALL <i style="width:4px;height:4px;border-radius:50%;background:${T.p700};display:block"></i> 3 ${I('chev', 18, T.sec)}</span>
  <div style="display:flex;gap:10px;align-items:center;margin-top:8px"><span style="display:flex;gap:3px"><i style="width:13px;height:3.5px;border-radius:2px;background:${T.cyan};display:block"></i><i style="width:13px;height:3.5px;border-radius:2px;background:${T.cyan};display:block"></i><i style="width:13px;height:3.5px;border-radius:2px;background:${T.yel};display:block"></i></span><span style="font:400 12px/16px Geist;color:${T.sec}">2 of 3 met</span></div></div>
 <div style="position:absolute;left:515px;top:-8px;padding:10px"><div style="display:flex;gap:4px;align-items:center;font:500 14px/20px Geist;color:#80c5ff"><i style="width:8px;height:8px;border-radius:50%;background:#80c5ff;display:block"></i>3x ${I('chev', 18, T.sec)}</div><div style="font:400 14px/20px Geist;color:${T.icon}">last 27 Jul, 3:42</div></div>
 <div style="position:absolute;left:692px;top:17px;display:flex;gap:16px;font:500 12px/16px Geist;color:${T.tx}"><span>Once Only</span><span>30 Jul, 9:00</span><span>Watch 1h close</span></div>
 <div style="position:absolute;left:957px;top:8px;display:flex;gap:12px">${['toast', 'mail'].map(k => `<span style="width:34px;height:34px;box-sizing:border-box;background:${T.inp};border:.5px solid ${T.b10};border-radius:4px;display:grid;place-items:center;color:${T.sec}">${I(k, 20)}</span>`).join('')}</div>
 <div style="position:absolute;left:1053px;top:11px;width:95px;display:flex;justify-content:space-between;align-items:center"><span style="color:${T.icon}">${I('edit', 24)}</span><span style="width:40px;height:22px;border-radius:12px;background:${T.p500};padding:2.9px;box-sizing:border-box;display:flex;justify-content:flex-end"><i style="width:17px;height:17px;border-radius:50%;background:${T.tx};display:block"></i></span></div></div>
 <div style="background:rgba(11,17,73,.5);border:1px solid ${T.b10};border-radius:10px;padding:10px;display:flex;gap:10px;align-items:center;font:500 12px/16px Geist;color:${T.tx};width:1142px;box-sizing:border-box"><b style="font-weight:600">3 Matches</b><i style="width:6px;height:6px;border-radius:50%;background:#80c5ff;display:block"></i>All 3 conditions held together<span style="display:flex;gap:6px;align-items:center;color:${T.sec}">${I('cal', 13)}last 27 Jul, 3:42 PM</span><span style="display:flex;gap:6px;align-items:center;color:${T.sec}">${I('cal', 13)}first 24 Jul, 9:06 AM</span></div>
 <div style="background:${T.inp};border:1px solid ${T.b10};border-radius:12px;padding:8px;box-sizing:border-box;width:100%;overflow:hidden">
  <div style="display:grid;grid-template-columns:34px 375px 142px 169px 102px 135px 30px;font:500 10px/12px Geist;color:${T.sec};padding:4px 7px 8px;border-bottom:1px solid ${T.b10};margin-bottom:4px"><span></span><span>CONDITION</span><span style="text-align:center">TOOLS</span><span>CONDITION</span><span style="text-align:center">STATUS</span><span style="text-align:center">MET</span><span>EDIT</span></div>
  ${cond.map((c, i) => `<div style="display:grid;grid-template-columns:34px 375px 142px 169px 102px 135px 30px;align-items:center;padding:6px 4px"><span style="display:grid;place-items:center">${dot(c[11] == '–' ? T.yel : T.green, c[10])}</span><span style="font:500 12px/16px Geist;color:${T.sec}">Condition ${i + 1}</span><span style="text-align:center">${pill(c[0], c[1], c[2])}</span><span><div style="font:600 14px/20px Geist;color:${T.tx}"><span style="color:${c[4]};margin-right:10px">${c[3]}</span>${c[5]}</div><div style="font:400 12px/16px Geist;color:${T.sec};margin-top:6px;display:flex;gap:5px"><span style="width:75px">${c[6]}</span><span>${c[7]}</span></div></span><span style="text-align:center"><span style="display:inline-block;background:${T.elev};border:1px solid ${T.b10};border-radius:16px;padding:2px 16px;font:500 14px/20px Geist;color:${c[9]}">${c[8]}</span></span><span style="text-align:center;font:500 12px Geist;color:${T.tx}">${c[11]}</span><span style="color:${T.icon}">${I('edit', 24)}</span></div>`).join('')}</div></div>` }

const dejaQuery = () => { const f = (l, v) => `<div style="flex:1"><div style="font:500 10px/12px Geist;color:${T.sec};margin-bottom:4px">${l}</div><div style="background:${T.inp};border:1px solid ${T.b10};border-radius:8px;padding:8px 12px;display:flex;justify-content:space-between;align-items:center;font:500 14px/20px Geist;color:${T.tx}">${v}<span style="color:${T.sec}">${I('chev', 22)}</span></div></div>`
  return `<div style="width:893px;height:170px;font-family:Geist;padding:10px 0 20px;box-sizing:border-box;display:flex;flex-direction:column;gap:16px"><div style="font:600 14px/20px Geist;color:${T.tx}">Structured Query</div>
 <div style="display:flex;gap:16px">${f('Regime (Temporal)', 'Breakout')}${f('Structure', 'POC &lt; 2%')}${f('Flow', 'Buyer dominant')}</div>
 <div style="display:flex;justify-content:space-between;align-items:center"><span style="display:flex;gap:8px;align-items:center;font:500 12px/16px Geist;color:${T.sec}">Cross-Asset Normalization<span style="display:inline-flex;background:${T.inp};border:.5px solid ${T.b10};border-radius:4px;padding:2px">${[['Percentile', 1], ['Z-score', 0], ['Sector-rel', 0]].map(t => `<span style="padding:2px ${t[1] ? 8 : 12}px;border-radius:4px;font:${t[1] ? 600 : 500} 12px/16px Geist;color:${T.tx};${t[1] ? `background:${T.p300}` : ''}">${t[0]}</span>`).join('')}</span></span>
 <span style="display:flex;gap:4px;align-items:center;background:${T.inp};border:1px solid ${T.p500};border-radius:8px;padding:8px 16px;font:500 12px/16px Geist;color:${T.p700}">${I('search', 13, T.p700)}Find Look-alikes</span></div></div>` }

const dejaEmpty = () => `<div style="width:426px;font-family:Geist;text-align:center;display:flex;flex-direction:column;align-items:center;gap:16px"><div style="width:98px;height:97px;border-radius:50%;background:radial-gradient(closest-side,rgba(48,85,227,.35),rgba(48,85,227,0));display:grid;place-items:center;color:${T.p700}">${I('hist', 40, T.p700, 1.5)}</div><div><div style="font:600 18px/22px Geist;color:${T.tx}">Find historical look-alikes</div><div style="font:400 13px/20px Geist;color:${T.sec};margin-top:8px">Describe the current setup using the filters above, then run a search. Déjà Vu scans years of market history for structurally similar moments and shows you what happened next.</div></div></div>`

const fpSettings = () => `<div style="${flat};width:640px;height:401px;border-radius:24px;box-sizing:border-box;padding:24px 24px 20px;font-family:Geist;display:flex;flex-direction:column;gap:24px">
 <div style="display:flex;justify-content:space-between;align-items:center"><span style="font:600 20px/28px Geist;color:${T.tx}">Footprint settings</span><span style="color:${T.sec}">${I('x', 24)}</span></div>
 <div style="display:flex;gap:12px">${[['Visual', 1], ['Footer', 0], ['Appearance', 0]].map(t => `<span style="padding:4px 16px;border-radius:8px;font:${t[1] ? 600 : 500} 14px/20px Geist;color:${t[1] ? T.tx : T.sec};${t[1] ? `background:${T.p500}` : `background:${T.inp};border:1px solid ${T.b10}`}">${t[0]}</span>`).join('')}</div>
 <div style="display:flex;flex-direction:column;gap:12px"><div><div style="font:600 14px/20px Geist;color:${T.tx}">Display mode</div><div style="font:400 12px/16px Geist;color:${T.sec}">How each price level is drawn.</div></div>
 <div style="display:flex;gap:4px;padding:4px;background:${T.inp};border:1px solid ${T.b10};border-radius:14px">${[['Numbers', 1], ['Dual bars', 0], ['Single bar', 0], ['Heatmap', 0]].map(t => `<span style="flex:1;height:40px;border-radius:10px;display:grid;place-items:center;font:${t[1] ? 600 : 500} 14px Geist;color:${t[1] ? T.tx : T.sec};${t[1] ? `background:${T.p500}` : ''}">${t[0]}</span>`).join('')}</div></div>
 <div style="display:flex;justify-content:space-between;align-items:center"><div><div style="font:600 14px/20px Geist;color:${T.tx}">Volume profile</div><div style="font:400 12px/16px Geist;color:${T.sec}">Session profile down the right edge.</div></div><span style="width:32px;height:18px;border-radius:9px;background:${T.p300};padding:2px;box-sizing:border-box"><i style="display:block;width:14px;height:14px;border-radius:50%;background:${T.sec}"></i></span></div></div>`

// ---- footprint chart ----
function rng(a) { return function () { a |= 0; a = a + 0x6D2B79F5 | 0; let t = Math.imul(a ^ a >>> 15, 1 | a); t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t; return ((t ^ t >>> 14) >>> 0) / 4294967296 } }
const footprint = (W = 907, H = 589, cols = 11) => { const r = rng(11); const step = 20, top = 60800, rows = 22, rh = 20, x0 = 12, axisW = 74, cw = Math.floor((W - 24 - axisW) / cols), y0 = 72
  let price = 60420, candles = []
  for (let i = 0; i < cols; i++) { const open = price; const dir = r() > .42 ? 1 : -1; const len = 3 + Math.floor(r() * 5); const close = open + dir * step * len; const hi = Math.max(open, close) + step * Math.floor(r() * 3), lo = Math.min(open, close) - step * Math.floor(r() * 3); candles.push({ open, close, hi, lo }); price = close + (r() - .5) * step * 2; price = Math.round(price / step) * step; price = Math.max(60340, Math.min(60740, price)) }
  const rowY = p => y0 + (top - p) / step * rh
  let svg = ''
  for (let k = 0; k <= rows; k++) svg += `<line x1="${x0}" x2="${W - axisW + 10}" y1="${y0 + k * rh}" y2="${y0 + k * rh}" stroke="rgba(128,197,255,.08)"/>`
  for (let k = 0; k < rows; k += 2) svg += `<text x="${W - axisW + 18}" y="${y0 + k * rh + 14}" fill="${T.sec}" font-size="10" font-family="Geist">${(top - k * step).toLocaleString('en-US')}</text>`
  candles.forEach((c, i) => { const x = x0 + i * cw; const up = c.close >= c.open; const col = up ? T.green : T.red
    for (let p = c.hi; p >= c.lo; p -= step) { const inBody = p <= Math.max(c.open, c.close) && p >= Math.min(c.open, c.close); const vol = 80 + Math.floor(r() * 260) * (inBody ? 1.4 : .7); const ask = Math.round(vol * (up ? .5 + r() * .35 : .25 + r() * .3)); const bid = Math.round(vol - ask); const poc = Math.abs(p - ((c.hi + c.lo) / 2)) < step; const heavy = vol > 330
      svg += `<rect x="${x + 1}" y="${rowY(p) + 1}" width="${cw - 2}" height="${rh - 2}" rx="2" fill="${ask > bid ? 'rgba(69,255,181,' : 'rgba(255,89,113,'}${Math.min(.34, vol / 1100)})" ${poc ? `stroke="${T.yel}" stroke-width="1.4"` : ''}/><text x="${x + cw / 2}" y="${rowY(p) + 14}" text-anchor="middle" font-family="IBM Plex Mono" font-size="9.5" fill="${ask > bid ? T.green : T.red}" ${heavy ? 'font-weight="600"' : ''}>${bid}×${ask}</text>` }
    svg += `<line x1="${x + cw / 2}" x2="${x + cw / 2}" y1="${rowY(c.hi) - 2}" y2="${rowY(c.lo) + rh + 2}" stroke="${col}" stroke-width="1" opacity=".0"/>` })
  return `<div style="${cardBg};width:${W}px;height:${H}px;border-radius:16px;box-sizing:border-box;font-family:Geist;position:relative;overflow:hidden">
 <div style="display:flex;gap:8px;align-items:center;padding:16px 18px"><span style="font:600 16px/22px Geist;color:#fff">BTC/USD</span><span style="font:500 12px Geist;color:${T.sec}">· 30m · Footprint</span>
 <span style="margin-left:auto;display:flex;gap:6px">${['15m', '30m', '1h', '4h'].map((t, i) => `<span style="padding:2px 10px;border-radius:6px;font:${i == 1 ? 600 : 500} 12px/16px Geist;color:${T.tx};${i == 1 ? `background:${T.p500}` : `background:${T.inp};border:1px solid ${T.b10}`}">${t}</span>`).join('')}<span style="padding:2px 8px;border-radius:6px;background:${T.inp};border:1px solid ${T.b10};color:${T.sec}">${I('filter', 16)}</span></span></div>
 <div style="display:flex;gap:16px;padding:0 18px;font:500 12px Geist;color:${T.sec}"><span>O <b style="color:${T.tx};font-weight:500">60,540.0</b></span><span>H <b style="color:${T.tx};font-weight:500">60,640.0</b></span><span>L <b style="color:${T.tx};font-weight:500">60,520.0</b></span><span>C <b style="color:${T.green};font-weight:500">60,620.0</b></span></div>
 <svg width="${W}" height="${H}" style="position:absolute;left:0;top:0">${svg}</svg></div>` }

const logoMark = (s = 17) => `<span style="font:700 ${s}px/1 Geist;letter-spacing:.02em;background:linear-gradient(90deg,#2f7bff,#5cb5ff);-webkit-background-clip:text;color:transparent">JAADU2.0</span>`
const navTop = () => `<div style="position:absolute;left:0;top:0;width:1440px;height:70px;box-sizing:border-box;background:${T.glass};border-bottom:1px solid rgba(128,197,255,.06);display:flex;align-items:center;justify-content:space-between;padding:8px 24px;font-family:Geist"><div style="width:213px;padding-left:22px">${logoMark(26)}</div>
 <div style="width:391px;box-sizing:border-box;background:${T.comp};border:.5px solid ${T.icon};border-radius:8px;padding:8px;display:flex;gap:4px;align-items:center;font:400 12px/16px Geist;color:${T.sec}">${I('search', 14)}Search Strategies...</div>
 <div style="display:flex;gap:16px;align-items:center"><span style="border:1px solid ${T.b10};border-radius:8px;padding:8px 12px;font:500 14px/20px Geist;color:${T.tx}">States</span><span style="color:${T.tx}">${I('bell', 28)}</span></div></div>`
const navLeft = (active = 3) => `<div style="position:absolute;left:0;top:70px;width:70px;height:830px;box-sizing:border-box;background:${T.bg};border-right:1px solid rgba(128,197,255,.1);display:flex;flex-direction:column;align-items:center;justify-content:space-between;padding:24px 12px">
 <div style="height:312px;display:flex;flex-direction:column;justify-content:space-between">${['dash', 'chat', 'book', 'bulb', 'alarm'].map((k, i) => `<span style="width:46px;height:46px;box-sizing:border-box;border-radius:8px;display:grid;place-items:center;color:${i == active ? T.p700 : T.icon};${i == active ? `border:.5px solid rgba(255,255,255,.6);background:linear-gradient(180deg,rgba(0,66,255,.2),rgba(0,66,255,.45))` : ''}">${I(k, 26, i == active ? T.p700 : T.icon, 1.6)}</span>`).join('')}</div>
 <span style="width:32px;height:32px;border-radius:50%;background:#4198ff;display:grid;place-items:center;color:#fff;font:500 18px Geist">A</span></div>`
const bgGlow = `<div style="position:absolute;left:437px;top:-150px;width:716px;height:305px;background:radial-gradient(closest-side,rgba(40,90,255,.5),rgba(0,2,43,0));filter:blur(40px)"></div>`

// ---- full screens (1440 x 900) ----
const screenBase = (inner, active) => `<div style="position:relative;width:1440px;height:900px;background:${T.bg};overflow:hidden;font-family:Geist">${bgGlow}${inner}${navTop()}${navLeft(active)}</div>`
const hdr = (icon, title, sub) => `<div style="display:flex;gap:14px;align-items:center"><span style="width:40px;height:40px;box-sizing:border-box;border-radius:8px;background:${T.elev};border:1px solid ${T.b10};display:grid;place-items:center;color:${T.p700}">${I(icon, 24, T.p700)}</span><div><div style="font:600 16px/22px Geist;color:${T.tx}">${title}</div><div style="font:400 12px/16px Geist;color:${T.sec}">${sub}</div></div></div>`
const screenOvernight = () => screenBase(`<div style="position:absolute;left:119px;top:112px">${quantSide()}</div>
 <div style="position:absolute;left:493px;top:117px;width:893px;display:flex;flex-direction:column;gap:25px">${hdr('bulb', 'Overnight Discoveries', 'Nightly evolutionary campaign &nbsp;•&nbsp; Three-stage falsification')}
 <div style="border-bottom:1px solid rgba(128,197,255,.06);padding:10px 0 20px;display:flex;flex-direction:column;gap:24px;align-items:flex-end"><div style="display:flex;gap:12px;width:100%;align-items:flex-end"><div style="flex:1"><div style="font:500 12px/16px Geist;color:${T.sec};margin-bottom:8px">Coins</div><div style="background:${T.inp};border:1px solid ${T.b10};border-radius:8px;padding:8px 12px;display:flex;gap:6px;align-items:center;font:500 12px Geist;color:${T.tx}">${['BTC', 'ETH', 'SOL', 'BNB', 'XRP'].map(c => `<span style="background:${T.comp};border-radius:6px;padding:1px 8px">${c}</span>`).join('')}<span style="margin-left:auto;color:${T.sec}">${I('chev', 22)}</span></div></div>
 <div style="flex:1"><div style="font:500 12px/16px Geist;color:${T.sec};margin-bottom:8px">Timeframe</div><div style="height:40px;box-sizing:border-box;background:${T.comp};border:.5px solid ${T.b10};border-radius:8px;padding:4px;display:flex;gap:4px"><span style="flex:1;border-radius:4px;background:${T.p400};display:grid;place-items:center;font:600 12px Geist;color:${T.tx}">Intra-day</span><span style="flex:1;display:grid;place-items:center;font:500 12px Geist;color:${T.tx}">Swing</span></div></div></div>
 <span style="background:${T.inp};border:1px solid ${T.inp};border-radius:8px;padding:8px 14px;font:500 12px/16px Geist;color:${T.tx};display:flex;gap:8px;align-items:center">${I('spin', 12, T.p700)}Running...</span></div>
 <div style="margin-top:-6px">${campaign()}</div></div>`, 3)
const screenFootprint = () => screenBase(`<div style="position:absolute;left:112px;top:104px;display:flex;flex-direction:column;gap:21px"><div style="display:flex;gap:24px;align-items:center;height:52px;font:500 14px Geist;color:${T.sec}"><span style="display:flex;gap:10px;align-items:center;color:${T.tx};font:700 22px Geist">${btcCoin(32)}BTC/USD</span><span style="color:${T.green}">+2.14%</span><span>Vol 6.17B</span></div><img src="assets/footprint.png" style="width:907px;height:520px;border-radius:16px;display:block;box-shadow:0 0 0 1px rgba(255,255,255,.14)">${regime()}</div>
 <div style="position:absolute;left:1048px;top:104px;display:flex;flex-direction:column;gap:16px">${coinStats()}${watchlist()}${trades(5, 212)}</div>`, 0)
const screenDeja = () => screenBase(`<div style="position:absolute;left:119px;top:112px">${quantSide()}</div>
 <div style="position:absolute;left:492px;top:131px;width:893px">${hdr('hist', 'Deja Vu', 'Breakout-VAH-v3 · BTCUSDT 4h · 2024-06 → 2025-06 · 1y / 5s engine')}<div style="margin-top:16px;border-bottom:1px solid rgba(128,197,255,.06)">${dejaQuery()}</div></div>
 <div style="position:absolute;left:757px;top:477px">${dejaEmpty()}</div>`, 3)
const screenLibrary = () => screenBase(`<div style="position:absolute;left:119px;top:112px">${quantSide()}</div>
 <div style="position:absolute;left:500px;top:126px;width:891px;display:flex;flex-direction:column;gap:28px">${hdr('lib', 'Library', 'Regime-aware specialist routing &nbsp;•&nbsp; Delta Exchange testnet shadow-mode')}<div style="display:flex;flex-direction:column;gap:24px">${libTable()}${equity()}</div></div>`, 3)

// ---- design system pieces ----
const dsSeg = () => `<div style="display:flex;gap:4px;padding:4px;background:${T.inp};border:1px solid ${T.b10};border-radius:14px;width:592px;font-family:Geist">${[['Numbers', 1], ['Dual bars', 0], ['Single bar', 0], ['Heatmap', 0]].map(t => `<span style="flex:1;height:40px;border-radius:10px;display:grid;place-items:center;font:${t[1] ? 600 : 500} 14px Geist;color:${t[1] ? T.tx : T.sec};${t[1] ? `background:${T.p500}` : ''}">${t[0]}</span>`).join('')}</div>`
const dsTabs = () => `<div style="display:flex;gap:12px;font-family:Geist">${[['Visual', 1], ['Footer', 0], ['Appearance', 0]].map(t => `<span style="padding:4px 16px;border-radius:8px;font:${t[1] ? 600 : 500} 14px/20px Geist;color:${t[1] ? T.tx : T.sec};${t[1] ? `background:${T.p500}` : `background:${T.inp};border:1px solid ${T.b10}`}">${t[0]}</span>`).join('')}</div>`
const dsToggles = () => `<div style="display:flex;gap:28px;align-items:center;font-family:Geist"><span style="width:40px;height:22px;border-radius:12px;background:${T.p500};padding:2.9px;box-sizing:border-box;display:flex;justify-content:flex-end"><i style="width:17px;height:17px;border-radius:50%;background:${T.tx};display:block"></i></span><span style="width:40px;height:22px;border-radius:12px;background:${T.p300};padding:2.9px;box-sizing:border-box"><i style="display:block;width:17px;height:17px;border-radius:50%;background:${T.sec}"></i></span><span style="display:inline-flex;gap:6px;align-items:center;background:${T.inp};border:1px solid ${T.b10};border-radius:4px;padding:2px 8px;font:500 14px/20px Geist;color:${T.p700}">ALL • 3</span></div>`
const dsChips = () => `<div style="display:flex;gap:10px;flex-wrap:wrap;width:560px;font-family:Geist">${pill('Price', T.cyan, 'rgba(0,255,255,.1)')}${pill('POC', T.p700, T.comp)}${pill('Footprint', T.yel, 'rgba(255,189,103,.1)')}${pill('Volume', T.red, 'rgba(255,89,113,.1)')}${pill('ACTIVE', T.green, T.elev)}${pill('MET', T.p500, T.elev)}</div>`
const dsButtons = () => `<div style="display:flex;gap:16px;align-items:center;font-family:Geist"><span style="background:${T.p500};border:1px solid ${T.b10};border-radius:8px;padding:8px 16px;font:600 12px/16px Geist;color:${T.tx};display:flex;gap:4px;align-items:center">${I('plus', 16, T.tx)}New Lab Session</span><span style="background:${T.inp};border:1px solid ${T.p500};border-radius:8px;padding:8px 16px;font:500 12px/16px Geist;color:${T.p700};display:flex;gap:4px;align-items:center">${I('search', 13, T.p700)}Find Look-alikes</span><span style="background:${T.inp};border:1px solid ${T.b10};border-radius:10px;padding:10px 16px;font:500 14px/20px Geist;color:${T.sec}">Reset all to defaults</span></div>`
const dsInputs = () => `<div style="width:420px;font-family:Geist"><div style="font:500 12px/16px Geist;color:${T.sec};margin-bottom:8px">Coins</div><div style="background:${T.inp};border:1px solid ${T.b10};border-radius:8px;padding:8px 12px;display:flex;justify-content:space-between;align-items:center;font:500 14px/20px Geist;color:${T.mut}">Select at least 5 coins<span style="color:${T.sec}">${I('chev', 24)}</span></div></div>`

if (typeof module !== 'undefined') module.exports = {}

// ---- mobile chart prompt (Figma 3644:206616 "Demo - Mobile (docked to bottom)") ----
const promptCard = () => `<div style="width:393px;height:138px;box-sizing:border-box;font-family:Geist;background:rgba(31,60,139,.18);border:1px solid ${T.b10};border-radius:16px 16px 0 0;padding:12px 16px 8px;display:flex;flex-direction:column;gap:10px;backdrop-filter:blur(7px)">
 <div style="color:${T.sec}">${I('x', 24)}</div>
 <div style="background:${T.inp};border:1px solid ${T.b10};border-radius:12px;padding:8px 8px 8px 12px;display:flex;align-items:center;justify-content:space-between"><span style="display:flex;gap:8px;align-items:center;font:400 12px/16px Geist;color:${T.tx}"><span style="color:${T.p700}">${I('search', 18, T.p700)}</span>Why did price reject this level?<i style="width:1.5px;height:16px;background:${T.p500};display:block"></i></span>
 <span style="display:flex;gap:14px;align-items:center;color:${T.icon}">${ic('<rect x="9" y="3" width="6" height="12" rx="3"/><path d="M5 11a7 7 0 0014 0M12 18v3"/>', 24)}<span style="width:36px;height:36px;box-sizing:border-box;border-radius:10px;background:${T.p400};border:1px solid rgba(167,191,255,.3);display:grid;place-items:center;color:#fff">${ic('<path d="M12 19V5M6 11l6-6 6 6"/>', 22, '#fff', 2)}</span></span></div>
 <div style="height:22px;display:grid;place-items:center"><i style="width:134px;height:5px;border-radius:3px;background:${T.sec};display:block"></i></div></div>`
const screenMobile = () => `<div style="position:relative;width:393px;height:852px;background:${T.bg};overflow:hidden"><img src="assets/mobile-chart.png" style="position:absolute;left:0;top:0;width:393px;height:676px"><i style="position:absolute;left:170px;top:286px;width:12px;height:12px;border-radius:50%;background:${T.p500};box-shadow:0 0 0 6px rgba(89,133,255,.25);display:block"></i><div style="position:absolute;left:0;top:714px">${promptCard()}</div></div>`
