// Pulsefit CRM, rebuilt as HTML. Every name, number and date here is sample data.
(function(){
const $=(h)=>{const d=document.createElement('div');d.innerHTML=h.trim();return d.firstChild};
const PAL=[['#E3EEFF','#0063F8'],['#EFEAFF','#5233D6'],['#FFE9D6','#B45309'],['#E0F5EC','#0C7A52'],['#FFE4EA','#B4234A'],['#E3F2FA','#0B6E99']];
const av=(n,s)=>{const i=[...n].reduce((a,c)=>a+c.charCodeAt(0),0)%PAL.length,p=PAL[i];return `<span class="av${s?' s':''}" style="background:${p[0]};color:${p[1]}">${n.split(' ').map(x=>x[0]).join('').slice(0,2)}</span>`};
const I=(n)=>`<svg class="i"><use href="#i-${n}"/></svg>`;
const chip=(c,t)=>`<span class="chip ${c}">${t}</span>`;
const LOGO=window.PFMARK('color','mk');
const NAV=[['dash','Dashboard'],['users','Members'],['star','Leads'],['id','Staff'],['tag','Plans'],['mail','Communication'],['dumb','Equipment'],['heart','Workouts']];
const shell=(active,sub,subOn,inner)=>`<div class="u app"><aside class="side"><div class="logo">${LOGO}Pulsefit</div><div class="ws">${av('Sam Rivera',1)}My workspace<svg class="i chev"><use href="#i-chev"/></svg></div><nav class="nv">${NAV.map(([ic,l])=>`<div class="it${l===active?' on':''}">${I(ic)}${l}<svg class="i chev"><use href="#i-chev"/></svg></div>${l===active&&sub?`<div class="sub">${sub.map(s=>`<span class="${s===subOn?'on':''}">${s}</span>`).join('')}</div>`:''}`).join('')}</nav></aside><header class="top"><div class="srch">${I('search')}Search members, leads, plans</div><div class="sp"></div><div class="ic">${I('sliders')}</div><div class="ic">${I('bell')}<em></em></div>${av('Sam Rivera')}</header><main class="main">${inner}</main></div>`;
const ph=(crumbs,title,btn)=>`<div class="crumb">${crumbs.map((c,i)=>i==crumbs.length-1?`<b>${c}</b>`:`<span>${c}</span><span>/</span>`).join('')}</div><div class="ph"><h1>${title}</h1>${btn}</div>`;
// ---------- charts ----------
function lineChart(w,h,series,labels,max,tipIdx){
  const L=40,B=h-34,T=14,R=w-28,x=i=>L+(R-L)*i/(labels.length-1),y=v=>B-(B-T)*v/max;let s=`<svg width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" style="display:block">`;
  [0,25,50,75,100].forEach(v=>{const yy=y(v*max/100);s+=`<line x1="${L}" x2="${R}" y1="${yy}" y2="${yy}" stroke="#EEF0F6"/><text x="0" y="${yy+4}" font-size="11" fill="#7B8196" font-family="Inter">${Math.round(v*max/100)}</text>`});
  labels.forEach((l,i)=>s+=`<text x="${x(i)}" y="${h-10}" font-size="11.5" fill="#7B8196" text-anchor="middle" font-family="Inter">${l}</text>`);
  if(tipIdx!=null)s+=`<line x1="${x(tipIdx)}" x2="${x(tipIdx)}" y1="${T}" y2="${B}" stroke="#C9CEDF" stroke-dasharray="4 4"/>`;
  series.forEach(se=>{s+=`<polyline fill="none" stroke="${se.c}" stroke-width="2.4" stroke-linejoin="round" stroke-linecap="round" points="${se.d.map((v,i)=>x(i)+','+y(v)).join(' ')}"/>`+se.d.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="${i==tipIdx?5:3}" fill="#fff" stroke="${se.c}" stroke-width="2"/>`).join('')});
  return s+'</svg>'}
function barChart(w,h,groups,labels,max,cols,stack){
  const L=34,B=h-30,T=10,R=w-6,gw=(R-L)/labels.length;let s=`<svg width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" style="display:block">`;
  [0,.25,.5,.75,1].forEach(f=>{const yy=B-(B-T)*f;s+=`<line x1="${L}" x2="${R}" y1="${yy}" y2="${yy}" stroke="#EEF0F6"/><text x="0" y="${yy+4}" font-size="11" fill="#7B8196" font-family="Inter">${Math.round(max*f)}</text>`});
  labels.forEach((l,i)=>{const cx=L+gw*i+gw/2;s+=`<text x="${cx}" y="${h-9}" font-size="11.5" fill="#7B8196" text-anchor="middle" font-family="Inter">${l}</text>`;
    const vals=groups.map(g=>g[i]);
    if(stack){let acc=0;vals.forEach((v,k)=>{const bh=(B-T)*v/max;s+=`<rect x="${cx-16}" y="${B-bh-acc}" width="32" height="${bh}" rx="${k==vals.length-1?6:0}" fill="${cols[k]}"/>`;acc+=bh})}
    else{const bw=Math.min(18,gw/ (groups.length+1));vals.forEach((v,k)=>{const bh=(B-T)*v/max,xx=cx-(groups.length*bw+(groups.length-1)*4)/2+k*(bw+4);s+=`<rect x="${xx}" y="${B-bh}" width="${bw}" height="${bh}" rx="5" fill="${cols[k]}"/>`})}});
  return s+'</svg>'}
function funnel(w,h){
  const st=[['Cold','234','100%'],['Warm','146','62%'],['Hot','89','38%'],['In progress','49','21%'],['Converted','28','12%']],cw=w/5;let s=`<svg width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" style="display:block"><defs><linearGradient id="fg" x1="0" x2="1"><stop offset="0" stop-color="#F5B400" stop-opacity=".95"/><stop offset="1" stop-color="#F2704A" stop-opacity=".6"/></linearGradient></defs>`;
  const hs=[1,.62,.38,.21,.12].map(f=>f*(h-70)),cy=(h+30)/2;
  let top='',bot='';hs.forEach((hh,i)=>{const x0=i*cw,x1=(i+1)*cw,nh=hs[i+1]??hh;top+=`${x0},${cy-hh/2} ${x1},${cy-nh/2} `});
  [...hs].reverse().forEach((hh,k)=>{const i=hs.length-1-k,x0=i*cw,x1=(i+1)*cw,nh=hs[i+1]??hh;bot+=`${x1},${cy+nh/2} ${x0},${cy+hh/2} `});
  s+=`<polygon points="${top}${bot}" fill="url(#fg)"/>`;
  st.forEach((t,i)=>{const cx=i*cw+cw/2;s+=`<text x="${cx}" y="18" font-size="12.5" font-weight="500" fill="#4B5163" text-anchor="middle" font-family="Inter">${t[0]}</text><text x="${cx}" y="${h-10}" font-size="12" fill="#7B8196" text-anchor="middle" font-family="Inter">${t[1]} leads</text>`;
    if(i>0)s+=`<line x1="${i*cw}" x2="${i*cw}" y1="30" y2="${h-26}" stroke="#fff" stroke-opacity=".7"/>`;
    s+=`<rect x="${cx-24}" y="${cy-14}" width="48" height="28" rx="14" fill="#fff"/><text x="${cx}" y="${cy+5}" font-size="13" font-weight="600" fill="#14171F" text-anchor="middle" font-family="Poppins">${t[2]}</text>`});
  return s+'</svg>'}
function heat(){
  const hrs=['6 AM','7 AM','8 AM','9 AM','10 AM','11 AM','12 PM','1 PM','2 PM','3 PM','4 PM'],days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
  const base=[[1,2,3,5,6,6,3,2,1,1,1],[2,5,7,8,7,6,4,2,2,3,5],[2,5,8,8,7,5,4,3,2,3,6],[2,4,7,9,8,6,4,2,2,3,5],[2,5,8,8,7,5,3,2,2,3,6],[1,4,6,7,6,5,3,2,2,3,4],[1,2,3,4,5,5,4,3,1,1,1]];
  const col=v=>`rgba(20,160,107,${(.06+v*.1).toFixed(2)})`;
  return `<div style="display:grid;grid-template-columns:44px repeat(11,1fr);gap:6px;align-items:center;padding:0 24px 22px"><span></span>${hrs.map(h=>`<span style="font-size:11.5px;color:#7B8196;text-align:center">${h}</span>`).join('')}${days.map((d,r)=>`<span style="font-size:12px;color:#7B8196;font-weight:500">${d}</span>`+base[r].map(v=>`<span style="height:34px;border-radius:8px;background:${col(v)};display:grid;place-items:center;font-size:11.5px;font-weight:600;color:#fff">${v>=9?'92':''}</span>`).join('')).join('')}</div>`}
const kpi=(l,v,d,up,good,ic,bg,fg)=>`<div class="cd kp"><div class="l">${l}<span class="ic" style="background:${bg};color:${fg}">${I(ic)}</span></div><div class="v">${v}</div><div class="d">${chip(good?'g':'r',(up?'↑ ':'↓ ')+d)} vs last week</div></div>`;
const lead=(n,t,tc,sub,subc,btn)=>`<div class="lrow">${av(n)}<div class="tx"><div class="nm">${n}${t?chip(tc,t):''}</div><div class="sb ${subc}">${sub}</div></div>${btn||''}</div>`;
const fu=`<span class="btn sm">Follow up</span>`;
const L={};
L.stale=`<div class="u cd" id="c-stale" style="width:380px"><div class="ch"><span class="dot" style="background:#E58A00"></span><h3>Stale leads</h3><span class="cnt" style="background:var(--amb-s);color:#B26A00">7</span></div>${lead('Aarav Mehta','Hot','hot','No activity for 15 days','r',fu)}${lead('Diya Kapoor','Warm','warm','No activity for 12 days','r',fu)}${lead('Rohan Iyer','Hot','hot','No activity for 9 days','r',fu)}</div>`;
L.missed=`<div class="u cd" id="c-missed" style="width:380px"><div class="ch"><span class="dot" style="background:#E5484D"></span><h3>Missed follow-ups</h3><span class="cnt" style="background:var(--red-s);color:#C23A3F">5</span></div>${lead('Kabir Shah','Hot','hot','Missed by 3 days','r',fu)}${lead('Ananya Rao','Warm','warm','Missed by 2 days','r',fu)}${lead('Vikram Sethi','Hot','hot','Missed by 1 day','r',fu)}</div>`;
L.flags=`<div class="u cd" id="c-flags" style="width:380px"><div class="ch"><span class="dot" style="background:#6D4AFF"></span><h3>Low-quality leads</h3><span class="cnt" style="background:var(--vio-s);color:#5233D6">4</span></div>${lead('Nikhil Joshi','Cold','cold','Phone number missing','v','<span class="btn sm s">Edit</span>')}${lead('Tara Menon','Warm','warm','Objective missing','v','<span class="btn sm s">Edit</span>')}${lead('Arjun Bhat','Hot','hot','Lead source missing','v','<span class="btn sm s">Edit</span>')}</div>`;
L.kpis=`<div class="u" id="c-kpis" style="width:1120px;display:grid;grid-template-columns:repeat(4,1fr);gap:16px">${kpi('New leads','234','12%',1,1,'user-plus','var(--pri-s)','var(--pri)')+kpi('Demo booking rate','23%','5%',1,1,'cal','var(--grn-s)','var(--grn)')+kpi('Conversion rate','12%','3%',0,0,'flame','var(--amb-s)','var(--amb)')+kpi('Lost leads','65','8%',0,1,'alert','var(--red-s)','var(--red)')}</div>`;
L.trend=`<div class="u cd" id="c-trend" style="width:660px"><div class="ch"><h3>Lead flow</h3><span class="va">Last 4 weeks</span></div><div style="padding:0 20px">${lineChart(620,250,[{c:'#F5B400',d:[64,91,48,90]},{c:'#14A06B',d:[40,64,47,64]},{c:'#0063F8',d:[16,45,21,42]},{c:'#E5484D',d:[7,22,10,32]}],['Week 1','Week 2','Week 3','Week 4'],100,2)}</div><div class="lg"><span><i style="background:#F5B400"></i>New leads</span><span><i style="background:#14A06B"></i>Demo booked</span><span><i style="background:#0063F8"></i>Converted</span><span><i style="background:#E5484D"></i>Drop-offs</span></div></div>`;
L.source=`<div class="u cd" id="c-source" style="width:520px"><div class="ch"><h3>Conversion by source</h3><span class="chip b" style="margin-left:auto">12% overall</span></div><div style="padding:0 20px">${barChart(480,250,[[92,76,50,70,92],[58,44,30,50,56]],['Social','Website','Walk-ins','Referral','Ads'],100,['#FF8A5B','#14171F'])}</div><div class="lg"><span><i style="background:#FF8A5B"></i>Leads</span><span><i style="background:#14171F"></i>Converted</span></div></div>`;
L.funnel=`<div class="u cd" id="c-funnel" style="width:660px"><div class="ch"><h3>Lead status</h3><span class="va">April ▾</span></div><div style="padding:0 20px 20px">${funnel(620,230)}</div></div>`;
L.objective=`<div class="u cd" id="c-objective" style="width:520px"><div class="ch"><h3>Objective split</h3><span class="chip n" style="margin-left:auto">234 leads</span></div><div style="padding:0 20px">${barChart(480,230,[[28,45,22,32],[18,30,12,28]],['Body building','Weight loss','Cardio','Others'],60,['#14171F','#D6D9E6'],true)}</div><div class="lg"><span><i style="background:#14171F"></i>Converted</span><span><i style="background:#D6D9E6"></i>Leads</span></div></div>`;
const ag=(n,l,c,r,t,chipc,chipt)=>`<tr><td><div class="who">${av(n)}<b>${n}</b></div></td><td class="num">${l}</td><td class="num">${c}</td><td>${r}</td><td>${t}</td><td>${chip(chipc,chipt)}</td></tr>`;
L.agents=`<div class="u cd" id="c-agents" style="width:1120px"><div class="ch"><h3>Agent performance</h3><span class="va">4 Sep to 7 Oct 2024</span></div><table class="tbl"><tr><th>Agent</th><th>Leads assigned</th><th>Converted</th><th>Conversion</th><th>Avg response</th><th>Rating</th></tr>${ag('Priya Nambiar',64,11,'17%','2h 10m','g','Top performer')+ag('Karan Malhotra',58,8,'14%','3h 05m','b','Good')+ag('Neha Bansal',61,6,'10%','5h 40m','a','Average')+ag('Rahul Desai',51,3,'6%','9h 15m','r','Needs coaching')}</table></div>`;
L.atoms=`<div class="u cd" id="c-atoms" style="width:470px;padding:26px;display:flex;flex-direction:column;gap:24px"><div><div class="alab">Buttons</div><div style="display:flex;gap:10px"><span class="btn">Follow up</span><span class="btn s">Remind</span><span class="btn o">Cancel</span></div></div><div><div class="alab">Status chips</div><div style="display:flex;gap:8px;flex-wrap:wrap">${chip('hot','Hot')}${chip('warm','Warm')}${chip('cold','Cold')}${chip('g','Active')}${chip('a','Expiring')}${chip('r','Frozen')}${chip('v','Strength')}</div></div><div><div class="alab">Avatars</div><div style="display:flex;gap:10px">${av('Aarav Mehta')}${av('Diya Kapoor')}${av('Rohan Iyer')}${av('Meera Nair')}${av('Kabir Shah')}</div></div><div><div class="alab">Controls</div><div style="display:flex;gap:16px;align-items:center"><span class="sg"><span class="on">Morning</span><span>Evening</span></span><span style="height:40px;padding:0 16px;border-radius:10px;box-shadow:inset 0 0 0 1px var(--line);display:flex;align-items:center;gap:8px;color:var(--mut);font-size:14px">${I('search')}Search</span></div></div><div><div class="alab">Tile</div><div style="display:flex;gap:14px"><div class="cd kp" style="flex:1;padding:14px 16px"><div class="l" style="font-size:12px">New leads</div><div class="v" style="font-size:26px">234</div></div><div class="cd kp" style="flex:1;padding:14px 16px"><div class="l" style="font-size:12px">Conversion</div><div class="v" style="font-size:26px">12%</div></div></div></div></div>`;
const exp=(n,ph,ag,pl,pc,e,ec)=>`<tr><td><div class="who">${av(n)}<div><b>${n}</b><small>${ph}</small></div></div></td><td>${chip(pc,pl)}</td><td style="color:${ec};font-weight:600">${e}</td><td><span class="btn sm">Renew</span> <span class="btn sm s" style="margin-left:6px">Remind</span></td></tr>`;
L.expiring=`<div class="u cd" id="c-expiring" style="width:600px"><div class="ch"><h3>Expiring subscriptions</h3><span class="chip a">8 this week</span><span class="va">View all</span></div><table class="tbl"><tr><th>Member</th><th>Plan</th><th>Expires</th><th>Actions</th></tr>${exp('Aarav Mehta','+91 98201 44371','Priya Nambiar','Annual Elite','v','Today','#E5484D')+exp('Diya Kapoor','+91 98765 20318','Karan Malhotra','Monthly Starter','b','in 2 days','#E58A00')+exp('Rohan Iyer','+91 99870 15529','Neha Bansal','Quarterly Pro','g','in 5 days','#4B5163')+exp('Meera Nair','+91 97411 63084','Priya Nambiar','Monthly Starter','b','in 6 days','#4B5163')}</table></div>`;
const drop=(n,a,d,ag)=>`<tr><td><div class="who">${av(n)}<div><b>${n}</b><small>${ag}</small></div></div></td><td class="num" style="color:#0063F8">${a}%</td><td style="color:#C23A3F;font-weight:600">↓ ${d} pts</td><td><span class="btn sm">Follow up</span></td></tr>`;
L.drop=`<div class="u cd" id="c-drop" style="width:640px"><div class="ch"><h3>Attendance drop</h3><span class="va">View all</span></div><table class="tbl"><tr><th>Member</th><th>Attendance</th><th>Change</th><th></th></tr>${drop('Kabir Shah',42,28,'Karan Malhotra')+drop('Ananya Rao',53,19,'Neha Bansal')+drop('Vikram Sethi',68,14,'Rahul Desai')+drop('Isha Verma',40,31,'Sneha Kulkarni')}</table></div>`;
const fz=(n,d)=>`<div class="lrow">${av(n)}<div class="tx"><div class="nm">${n}</div><div class="sb">Frozen for ${d} days</div></div><span class="btn sm">Unfreeze</span></div>`;
L.frozen=`<div class="u cd" id="c-frozen" style="width:430px"><div class="ch"><h3>Frozen members</h3><span class="cnt" style="background:var(--pri-s);color:var(--pri-d)">26</span></div>${fz('Nikhil Joshi',15)+fz('Tara Menon',12)+fz('Arjun Bhat',9)}</div>`;
L.kpim=`<div class="u" id="c-kpim" style="width:300px">${kpi('Active members','1,043','4%',1,1,'users','var(--pri-s)','var(--pri)')}</div>`;
L.heat=`<div class="u cd" id="c-heat" style="width:1120px"><div class="ch" style="padding:22px 24px 18px"><h3>Attendance by hour</h3><span class="sg" style="margin-left:auto"><span class="on">Morning</span><span>Evening</span></span></div>${heat()}</div>`;
L.plansby=`<div class="u cd" id="c-plansby" style="width:640px"><div class="ch"><h3>Members by plan</h3><span class="chip n" style="margin-left:auto">1,043 members</span></div><div style="padding:0 20px 14px">${barChart(600,240,[[86,34,48,72,52,80,64,46,26,60]],['Starter','Student','Couples','Pro','Plus','Elite','Yoga','AM','PM','Flex'],100,['#14171F'])}</div></div>`;
const st=(id,n,ph,em,t,tc,des)=>`<tr><td style="color:var(--mut)">${id}</td><td><div class="who">${av(n)}<b>${n}</b></div></td><td>${ph}</td><td style="color:var(--t2)">${em}</td><td>${chip(tc,t)}</td><td>${des}</td></tr>`;
L.staff=`<div class="u cd" id="c-staff" style="width:900px"><div class="ch"><h3>Staff</h3><span class="va" style="gap:8px">${I('search')}Search</span></div><table class="tbl"><tr><th>ID</th><th>Employee</th><th>Contact</th><th>Email</th><th>Type</th><th>Role</th></tr>${st('S-101','Priya Nambiar','+91 98201 44371','priya@pulsefit.example','Permanent','v','Gym manager')+st('S-102','Karan Malhotra','+91 98765 20318','karan@pulsefit.example','Permanent','v','Assistant manager')+st('S-103','Neha Bansal','+91 99870 15529','neha@pulsefit.example','Freelancer','a','Personal trainer')+st('S-104','Rahul Desai','+91 97411 63084','rahul@pulsefit.example','Consultant','r','Nutritionist')}</table></div>`;
const eq=(c,cc,m,q,d,p,s)=>`<tr><td>${chip(cc,c)}</td><td><b>${m}</b></td><td class="num">${q}</td><td style="color:var(--t2)">${d}</td><td class="num">${p}</td><td>${chip(s=='Scheduled'?'g':'a',s)}</td></tr>`;
L.equip=`<div class="u cd" id="c-equip" style="width:900px"><div class="ch"><h3>All equipment</h3><span class="btn sm" style="margin-left:auto">${I('plus')}Add equipment</span></div><table class="tbl"><tr><th>Category</th><th>Model</th><th>Qty</th><th>Purchased</th><th>Cost</th><th>Repair</th></tr>${eq('Cardio','b','Treadmill TX-200',6,'12 Mar 2024','₹ 62,000','Scheduled')+eq('Strength','v','Flat bench FB-40',8,'02 Jun 2024','₹ 18,500','Unscheduled')+eq('Cardio','b','Rower R-300',4,'20 Dec 2024','₹ 48,000','Scheduled')+eq('Studio','g','Spin bike SB-90',12,'15 Jan 2025','₹ 31,200','Scheduled')}</table></div>`;
L.leadform=`<div class="u cd" id="c-leadform" style="width:900px;display:grid;grid-template-columns:250px 1fr"><div style="padding:24px;border-right:1px solid var(--line)"><h3 style="font-size:17px;font-weight:600">Create lead</h3><div style="color:var(--mut);margin:4px 0 20px">Three short steps</div>${[['Lead details',1],['Qualification and action',0],['Follow-up details',0]].map(([t,on],i)=>`<div style="display:flex;align-items:center;gap:12px;height:40px;font-weight:${on?600:500};color:${on?'var(--ink)':'var(--mut)'}"><span style="width:24px;height:24px;border-radius:50%;display:grid;place-items:center;font-size:12px;font-weight:600;${on?'background:var(--pri);color:#fff':'box-shadow:inset 0 0 0 1.5px var(--line)'}">${i+1}</span>${t}</div>`).join('')}</div><div style="padding:24px 28px"><h3 style="font-size:16px;font-weight:600;margin-bottom:16px">Personal information</h3><div style="display:grid;grid-template-columns:1fr 1fr;gap:16px">${['First name','Last name','Email','Phone number'].map((t,i)=>`<div><div style="color:var(--t2);font-weight:500;margin-bottom:6px">${t}</div><div style="height:40px;border-radius:10px;box-shadow:inset 0 0 0 1px var(--line);padding:0 12px;display:flex;align-items:center;color:var(--mut)">${['Aarav','Mehta','aarav.m@example.com','+91 98201 44371'][i]}</div></div>`).join('')}</div><div style="display:flex;gap:10px;margin-top:20px"><span style="color:var(--t2);font-weight:500;margin-right:6px;align-self:center">Status</span>${chip('hot','Hot')}${chip('n','Warm')}${chip('n','Cold')}</div><div style="display:flex;justify-content:flex-end;margin-top:20px"><span class="btn">Next ${I('chev')}</span></div></div></div>`;
// ---------- the three full apps ----------
const hm=`<div class="u" id="app-leads">${shell('Leads',['Dashboard','Create lead','Leads table'],'Dashboard',ph(['Leads','Tasks'],'Lead tasks',`<span class="btn">${I('plus')}New lead</span>`)+`<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:20px">${L.stale.replace('width:380px','')}${L.missed.replace('width:380px','')}${L.flags.replace('width:380px','')}</div><div style="display:flex;justify-content:space-between;align-items:center;margin:26px 0 14px"><h2 class="hd" style="font-size:20px;font-weight:600">Lead performance</h2><span class="va" style="display:flex;gap:8px;height:34px;padding:0 12px;border-radius:10px;box-shadow:inset 0 0 0 1px var(--line);background:#fff;align-items:center;font-size:13px">${I('cal')}4 Sep to 7 Oct 2024</span></div><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:16px">${kpi('New leads','234','12%',1,1,'user-plus','var(--pri-s)','var(--pri)')+kpi('Demo booking rate','23%','5%',1,1,'cal','var(--grn-s)','var(--grn)')+kpi('Conversion rate','12%','3%',0,0,'flame','var(--amb-s)','var(--amb)')+kpi('Lost leads','65','8%',0,1,'alert','var(--red-s)','var(--red)')}</div>`)}</div>`;
const mm=`<div class="u" id="app-members">${shell('Members',['Dashboard','Add member','Members table'],'Dashboard',ph(['Members','Tasks'],'Member tasks',`<span class="btn">${I('plus')}Add member</span>`)+`<div style="display:grid;grid-template-columns:1.55fr 1fr;gap:20px">${L.expiring.replace('width:600px','')}${L.frozen.replace('width:430px','')}</div><div style="margin-top:20px">${L.drop.replace('width:640px','')}</div>`)}</div>`;
const lib=document.getElementById('lib');
lib.innerHTML=Object.values(L).join('')+hm+mm;
// plans app built separately (clean data rows)
const planData=[['Strength','#5233D6','var(--vio-s)','Quarterly Pro','3 months','₹ 3,200','₹ 576','10 days','84'],['Cardio','#003A92','var(--pri-s)','Monthly Starter','1 month','₹ 1,200','₹ 216','14 days','212'],['Yoga','#0C7A52','var(--grn-s)','Half-year Plus','6 months','₹ 5,800','₹ 1,044','21 days','61'],['Mixed','#B26A00','var(--amb-s)','Annual Elite','12 months','₹ 9,900','₹ 1,782','30 days','47'],['Strength','#5233D6','var(--vio-s)','Student Flex','1 month','₹ 900','₹ 162','7 days','96'],['Cardio','#003A92','var(--pri-s)','Morning Batch','1 month','₹ 1,000','₹ 180','7 days','73'],['Yoga','#0C7A52','var(--grn-s)','Weekend Only','1 month','₹ 800','₹ 144','4 days','38'],['Mixed','#B26A00','var(--amb-s)','Couples Duo','3 months','₹ 5,400','₹ 972','14 days','29']];
const card=(p)=>`<div class="cd plan"><span class="chip cat" style="background:${p[2]};color:${p[1]}">${p[0]}</span><h3>${p[3]}</h3><div class="kv"><div><small>Duration</small><b>${p[4]}</b></div><div><small>Amount</small><b>${p[5]}</b></div><div><small>Taxes</small><b>${p[6]}</b></div><div><small>Pause days</small><b>${p[7]}</b></div></div><div class="ft"><div class="tx"><b>${p[8]}</b>active members</div><span class="btn sm s">View plan</span></div></div>`;
const plansApp=`<div class="u" id="app-plans">${shell('Plans',['All plans','Add plan'],'All plans',ph(['Plans'],'Plans',`<span class="btn">${I('plus')}Add plan</span>`)+`<div class="tabs"><span class="on">Active plans</span><span>Deleted plans</span></div><div class="pgrid">${planData.slice(0,8).map(card).join('')}</div>`)}</div>`;
lib.insertAdjacentHTML('beforeend',plansApp);
lib.insertAdjacentHTML('beforeend',`<div id="c-plancards" class="u" style="display:flex;gap:18px;width:640px">${card(planData[0]).replace('class="cd plan"','class="cd plan" style="width:310px"')}${card(planData[1]).replace('class="cd plan"','class="cd plan" style="width:310px"')}</div>`);
})();
