// SSH client v2 product UI: helpers, the app shell and the screens used in the modules. Every name and number is sample data.
(function(){
const P = {}
window.P = P
const ICONS = {
  search: '<circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/>',
  bell: '<path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"/><path d="M10.3 21a1.9 1.9 0 0 0 3.4 0"/>',
  gear: '<circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M4.2 4.2l2.1 2.1M17.7 17.7l2.1 2.1M2 12h3M19 12h3M4.2 19.8l2.1-2.1M17.7 6.3l2.1-2.1"/>',
  plus: '<path d="M12 5v14M5 12h14"/>', chev: '<path d="m6 9 6 6 6-6"/>', chevR: '<path d="m9 6 6 6-6 6"/>', arrowL: '<path d="M19 12H5M11 6l-6 6 6 6"/>', arrowR: '<path d="M5 12h14M13 6l6 6-6 6"/>',
  server: '<rect x="3" y="4" width="18" height="7" rx="2"/><rect x="3" y="13" width="18" height="7" rx="2"/><path d="M7 7.5h.01M7 16.5h.01"/>',
  term: '<rect x="3" y="4" width="18" height="16" rx="2"/><path d="m7 9 3 3-3 3M13 15h4"/>',
  ports: '<path d="M7 7h11l-3-3M17 17H6l3 3"/>', folder: '<path d="M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/>',
  key: '<circle cx="8" cy="15" r="4"/><path d="m11 12 9-9M16 7l3 3M14 9l2 2"/>', users: '<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.9M16 3.1a4 4 0 0 1 0 7.8"/>',
  more: '<circle cx="5" cy="12" r="1.2"/><circle cx="12" cy="12" r="1.2"/><circle cx="19" cy="12" r="1.2"/>', x: '<path d="M18 6 6 18M6 6l12 12"/>',
  check: '<path d="M20 6 9 17l-5-5"/>', chart: '<path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/>', file: '<path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"/><path d="M14 3v6h6"/>',
  shield: '<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>', info: '<circle cx="12" cy="12" r="9"/><path d="M12 16v-4M12 8h.01"/>', alert: '<path d="m21.7 18-8-14a2 2 0 0 0-3.4 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.7-3"/><path d="M12 9v4M12 17h.01"/>',
  down: '<path d="M12 5v14M6 13l6 6 6-6"/>', up: '<path d="M12 19V5M6 11l6-6 6 6"/>', cpu: '<rect x="6" y="6" width="12" height="12" rx="2"/><path d="M9 2v4M15 2v4M9 18v4M15 18v4M2 9h4M2 15h4M18 9h4M18 15h4"/>',
  spark: '<path d="M12 3l1.9 5.6L19.5 10l-5.6 1.9L12 17.5l-1.9-5.6L4.5 10l5.6-1.4z"/>', box: '<path d="m21 8-9-5-9 5 9 5z"/><path d="M3 8v8l9 5 9-5V8M12 13v8"/>',
  history: '<path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5M12 7v5l3 2"/>', copy: '<rect x="9" y="9" width="12" height="12" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/>',
  play: '<path d="m7 4 13 8-13 8z"/>', send: '<path d="m22 2-7 20-4-9-9-4z"/><path d="M22 2 11 13"/>', globe: '<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a14 14 0 0 1 0 18M12 3a14 14 0 0 0 0 18"/>',
  lock: '<rect x="4" y="11" width="16" height="10" rx="2"/><path d="M8 11V7a4 4 0 0 1 8 0v4"/>', grid: '<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
  list: '<path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01"/>', edit: '<path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4z"/>',
}
const i = (n, st = '') => `<svg class="i" viewBox="0 0 24 24"${st ? ` style="${st}"` : ''}>${ICONS[n]}</svg>`
P.i = i
// OS marks, drawn simply
const OS = {
  ubuntu: '<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="6.5" fill="none" stroke="#F97316" stroke-width="2.6"/><circle cx="5" cy="12" r="2.4" fill="#F97316"/><circle cx="15.5" cy="5.9" r="2.4" fill="#F97316"/><circle cx="15.5" cy="18.1" r="2.4" fill="#F97316"/></svg>',
  arch: '<svg viewBox="0 0 24 24"><path d="M12 2.5 3 21.5c2.6-1.7 5-2.6 6-2.2.4-2.1 1.5-3.6 3-3.6s2.6 1.5 3 3.6c1-.4 3.4.5 6 2.2z" fill="#38BDF8"/></svg>',
  debian: '<svg viewBox="0 0 24 24"><path d="M15.5 17.5a7 7 0 1 1 3-8.5" fill="none" stroke="#F43F5E" stroke-width="2.4" stroke-linecap="round"/><path d="M14 14.5a3 3 0 1 1 1.4-4" fill="none" stroke="#F43F5E" stroke-width="2.2" stroke-linecap="round"/></svg>',
  fedora: '<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9" fill="#3B82F6"/><path d="M10 18v-7a3 3 0 0 1 5-2.2M8 12h6" fill="none" stroke="#fff" stroke-width="2.2" stroke-linecap="round"/></svg>',
}
P.os = k => `<span class="os">${OS[k]}</span>`
const AVC = [['rgba(111,142,245,.18)', '#A9BCFF'], ['rgba(52,211,153,.16)', '#6EE7B7'], ['rgba(251,191,36,.16)', '#FCD34D'], ['rgba(244,114,182,.16)', '#F9A8D4'], ['rgba(56,189,248,.16)', '#7DD3FC']]
const ini = n => n.split(' ').map(s => s[0]).join('').slice(0, 2)
const av = (n, sm) => { const [b, c] = AVC[[...n].reduce((a, ch) => a + ch.charCodeAt(0), 0) % AVC.length]; return `<span class="av${sm ? ' sm' : ''}" style="background:${b};color:${c}">${ini(n)}</span>` }
const tag = (t, c, d) => `<span class="tag t-${c}">${d ? '<span class="d"></span>' : ''}${t}</span>`
Object.assign(P, { av, tag })

// ---- shell ----
const NAV = [['server', 'Hosts'], ['term', 'Terminal'], ['key', 'Keys'], ['ports', 'Port mapping'], ['folder', 'SFTP'], ['users', 'Sessions']]
P.shell = (active, content, { tab = active, vault = true } = {}) => `<div class="app u"><aside class="side"><div class="brand"><img src="mark.svg"></div>
  <div class="nl">Workspace</div>${NAV.map(([ic, n]) => `<div class="it${n === active ? ' on' : ''}">${i(ic)}${n}${n === 'Sessions' ? '<span class="n">5</span>' : ''}</div>`).join('')}
  <div class="nl" style="margin-top:8px">Vaults</div><div class="it"><span class="dot" style="background:var(--pri)"></span>Personal</div><div class="it"><span class="dot" style="background:var(--grn)"></span>Team · Platform</div>
  <div class="me">${av('Ira Sen')}<div>Ira Sen<small>ira@platform.dev</small></div><span class="ib" style="margin-left:auto">${i('gear')}</span></div></aside>
  <div class="main"><div class="top"><span class="ib b">${i('arrowL')}</span><span class="ib b">${i('arrowR')}</span><div class="search">${i('search')}Search hosts, keys, commands<kbd>⌘K</kbd></div><div style="margin-left:auto"></div><span class="ib">${i('bell')}</span>${vault ? `<span class="btn s">${i('lock')}Personal vault${i('chev')}</span>` : ''}</div>
  <div class="body">${content}</div></div></div>`
const head = (crumb, title, sub, acts = '') => `<div class="ph"><div><div class="crumb">${crumb.map((c, k) => k < crumb.length - 1 ? `${c}${i('chevR', 'width:12px;height:12px')}` : `<b>${c}</b>`).join('')}</div><h1>${title}</h1>${sub ? `<div class="sub2">${sub}</div>` : ''}</div><div class="acts">${acts}</div></div>`
P.head = head

// ---- hosts ----
const HOSTS = [['API Gateway', 'ubuntu', '10.0.1.12', 'Production', 'on', ['api', 'edge']], ['Cloud-instance-01', 'arch', '10.0.1.24', 'Production', 'on', ['compute']], ['DB-master', 'fedora', '10.0.2.5', 'Production', 'on', ['db']], ['Staging-server', 'debian', '10.0.3.18', 'Staging', 'on', ['web']], ['Jump-server', 'ubuntu', '10.0.0.2', 'Shared', 'on', ['bastion']], ['Dev-api-01', 'arch', '10.0.4.31', 'Development', 'off', ['api']], ['Apache-02', 'fedora', '10.0.3.40', 'Staging', 'off', ['web']]]
P.HOSTS = HOSTS
const envTag = e => tag(e, { Production: 'pri', Staging: 'amb', Development: 'cy', Shared: 'gray' }[e])
P.hostRow = ([n, os, ip, env, st, tags], noTags) => `<tr><td><div class="who">${P.os(os)}<div style="font-weight:600">${n}<small class="mono" style="font-size:11.5px">${ip}:22</small></div></div></td><td>${envTag(env)}</td>${noTags ? '' : `<td>${tags.map(t => `<span class="tag t-gray" style="margin-right:4px">${t}</span>`).join('')}</td>`}<td><span style="display:inline-flex;align-items:center;gap:7px;color:${st === 'on' ? '#6EE7B7' : 'var(--mut)'}"><span class="dot" style="background:${st === 'on' ? 'var(--grn)' : '#4B5168'}"></span>${st === 'on' ? 'Online' : 'Offline'}</span></td><td class="r"><span style="display:inline-flex;gap:4px;color:var(--t2)"><span class="ib b" style="width:30px;height:30px">${i('chart', 'width:14px;height:14px')}</span><span class="ib b" style="width:30px;height:30px">${i('folder', 'width:14px;height:14px')}</span><span class="btn sm s">${i('term')}Connect</span></span></td></tr>`
P.hostsCard = (n = 7, noTags) => `<div class="card u" style="overflow:hidden"><table class="tbl"><tr><th>Host</th><th>Group</th>${noTags ? '' : '<th>Tags</th>'}<th>Status</th><th class="r">Actions</th></tr>${HOSTS.slice(0, n).map(h => P.hostRow(h, noTags)).join('')}</table></div>`
P.newHost = (h) => `<div class="panel u" style="width:420px;${h ? `height:${h}px;` : ''}display:flex;flex-direction:column">
  <div class="ph2"><span class="ico" style="background:var(--pri-s);color:var(--pri)">${i('server')}</span><h2>New host</h2><span class="ib" style="margin-left:auto">${i('x')}</span></div>
  <div style="padding:16px 18px 0"><span class="seg" style="width:100%"><span class="on" style="flex:1;justify-content:center">Connection</span><span style="flex:1;justify-content:center">Login</span><span style="flex:1;justify-content:center">Advanced</span></span></div>
  <div style="padding:18px;display:flex;flex-direction:column;gap:16px">
    <div style="display:grid;grid-template-columns:1fr 90px;gap:12px"><div class="fl">Address<div class="inp foc mono" style="font-size:13px">10.0.5.20</div></div><div class="fl">Port<div class="inp mono" style="font-size:13px">22</div></div></div>
    <div class="fl">Label<div class="inp">Billing-worker</div></div>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px"><div class="fl">Group<div class="inp">${envTag('Production')}<span class="sfx">${i('chev')}</span></div></div><div class="fl">Tags<div class="inp"><span class="tag t-gray">worker</span><span class="sfx">${i('chev')}</span></div></div></div>
    <div class="fl">Login with<div class="inp">${i('key', 'color:var(--pri)')}ira-laptop · ED25519<span class="sfx">${i('chev')}</span></div></div>
    <div style="display:flex;align-items:center;gap:10px;font-size:13px;color:var(--t2)"><span class="tg on"></span>Show live stats after connecting</div>
  </div>
  <div style="margin-top:auto;display:flex;gap:10px;padding:16px 18px;border-top:1px solid var(--line)"><span class="btn g">Cancel</span><span class="btn p" style="margin-left:auto">${i('term')}Save and connect</span></div></div>`
P.hostsFrame = () => P.shell('Hosts', `<div style="display:flex;gap:18px;align-items:flex-start"><div style="flex:1;min-width:0;display:flex;flex-direction:column;gap:18px">
  ${head(['Hosts'], 'Hosts', '7 hosts · 5 online', `<span class="seg"><span class="on">${i('list', 'width:14px;height:14px')}</span><span>${i('grid', 'width:14px;height:14px')}</span></span><span class="btn p">${i('plus')}New host</span>`)}
  <div style="display:flex;gap:8px"><span class="seg"><span class="on">All · 7</span><span>Production · 3</span><span>Staging · 2</span><span>Development · 1</span><span>Shared · 1</span></span></div>
  ${P.hostsCard()}</div>${P.newHost(620)}</div>`)

// ---- host overview ----
P.security = () => `<div class="card u" style="overflow:hidden"><div class="ch"><span class="ico" style="background:var(--grn-s);color:var(--grn)">${i('shield')}</span><h3>Security checks</h3><span style="margin-left:auto;font-size:12.5px;color:var(--mut)">4 passed · 1 warning</span></div>
  ${[['ok', 'SSH uses key-based login'], ['ok', 'Firewall on, 3 rules'], ['warn', 'Disk /dev/sda1 is 86% full'], ['ok', 'All packages up to date'], ['ok', 'Last login: ira from 10.0.0.2']].map(([s, t]) => `<div style="display:flex;align-items:center;gap:12px;padding:12px 18px;border-top:1px solid var(--line)">${s === 'ok' ? tag('Pass', 'grn', 1) : tag('Warn', 'amb', 1)}<span style="color:${s === 'ok' ? 'var(--t2)' : 'var(--tx)'}">${t}</span>${s === 'warn' ? '<span class="btn sm s" style="margin-left:auto">Open storage</span>' : ''}</div>`).join('')}</div>`
const spark = (vals, c) => { const w = 260, h = 46, mx = Math.max(...vals); const bw = w / vals.length; return `<svg width="${w}" height="${h}">${vals.map((v, k) => `<rect x="${k * bw + 1.5}" y="${h - v / mx * h}" width="${bw - 3}" height="${v / mx * h}" rx="2" fill="${c}" opacity="${.35 + .65 * k / vals.length}"/>`).join('')}</svg>` }
P.network = () => `<div class="card u" style="padding:18px"><div style="display:flex;align-items:center;gap:10px"><span class="ico" style="background:var(--cy-s);color:var(--cy)">${i('globe')}</span><h3>Network · eth0</h3><span class="tag t-grn" style="margin-left:auto"><span class="d"></span>Live</span></div>
  <div style="display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:16px">${[['down', 'Download', '1.1', '#A9BCFF', [3, 4, 3, 5, 4, 6, 5, 7, 6, 5, 8, 7, 9, 8, 11, 9, 12, 10, 14, 11]], ['up', 'Upload', '1.6', '#6EE7B7', [2, 3, 4, 3, 5, 4, 6, 5, 7, 6, 6, 8, 7, 9, 8, 10, 9, 12, 13, 12]]].map(([ic, l, v, c, d]) => `<div style="border-radius:12px;background:var(--card2);box-shadow:inset 0 0 0 1px var(--line);padding:14px 16px"><div style="display:flex;align-items:center;gap:8px;color:var(--t2);font-size:12.5px">${i(ic, `width:14px;height:14px;color:${c}`)}${l}</div><div style="font-size:24px;font-weight:650;margin:6px 0 10px;color:${c}">${v}<span style="font-size:13px;color:var(--mut);font-weight:500"> MB/s</span></div>${spark(d, c).replace('width="260"', 'width="100%" viewBox="0 0 260 46" preserveAspectRatio="none"')}</div>`).join('')}</div>
  <div style="display:flex;gap:18px;margin-top:14px;font-size:12.5px;color:var(--mut)"><span>Ping <b style="color:var(--tx)">24 ms</b></span><span>Received <b style="color:var(--tx)">8.7 GB</b></span><span>Sent <b style="color:var(--tx)">6.2 GB</b></span></div></div>`
P.cpu = () => {
  const pts = [38, 30, 26, 28, 35, 44, 52, 61, 72, 64, 55, 58, 49, 41, 47, 56, 63, 67, 60, 52], w = 560, h = 160
  const xy = pts.map((v, k) => [k / (pts.length - 1) * w, h - v / 100 * h])
  const d = 'M' + xy.map(p => p.join(' ')).join(' L')
  const cores = [75, 42, 35, 61, 25, 50, 38, 30]
  return `<div class="card u" style="padding:18px 20px"><div style="display:flex;align-items:center;gap:10px"><span class="ico" style="background:var(--pri-s);color:var(--pri)">${i('cpu')}</span><h3>CPU</h3><span style="color:var(--mut);font-size:12.5px">Intel Xeon E5-2676 · 8 cores</span><span class="seg" style="margin-left:auto"><span>1h</span><span class="on">24h</span><span>7d</span></span></div>
  <div style="display:grid;grid-template-columns:1fr 240px;gap:28px;margin-top:16px;align-items:end">
   <div><div style="display:flex;gap:26px;margin-bottom:12px">${[['Usage', '45%'], ['Temperature', '62°C'], ['Load', '1.02 · 0.88 · 0.95']].map(([l, v]) => `<div><div style="color:var(--mut);font-size:12px">${l}</div><div style="font-size:18px;font-weight:650;margin-top:2px">${v}</div></div>`).join('')}</div>
    <svg width="100%" viewBox="0 0 ${w} ${h + 18}" style="display:block"><defs><linearGradient id="cg" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#8B5CF6"/><stop offset="1" stop-color="#38BDF8"/></linearGradient><linearGradient id="cf" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#8B5CF6" stop-opacity=".35"/><stop offset="1" stop-color="#8B5CF6" stop-opacity="0"/></linearGradient></defs>
     ${[0, .25, .5, .75, 1].map(f => `<line x1="0" x2="${w}" y1="${f * h}" y2="${f * h}" stroke="#232737"/>`).join('')}<path d="${d} L${w} ${h} L0 ${h}Z" fill="url(#cf)"/><path d="${d}" fill="none" stroke="url(#cg)" stroke-width="2.5"/>
     ${['00:00', '06:00', '12:00', '18:00', 'Now'].map((t, k) => `<text x="${k / 4 * w}" y="${h + 15}" fill="#6F7792" font-size="11" text-anchor="${k === 0 ? 'start' : k === 4 ? 'end' : 'middle'}" font-family="Inter">${t}</text>`).join('')}</svg></div>
   <div style="display:flex;flex-direction:column;gap:9px"><div style="color:var(--t2);font-size:12.5px;font-weight:600;margin-bottom:2px">Per core</div>${cores.map((c, k) => `<div style="display:grid;grid-template-columns:44px 1fr 34px;gap:8px;align-items:center;font-size:11.5px;color:var(--mut)">Core ${k + 1}<div class="bar"><i style="width:${c}%;background:${c > 70 ? 'var(--amb)' : c > 55 ? 'var(--cy)' : 'var(--pri)'}"></i></div><span style="text-align:right;color:var(--tx)">${c}%</span></div>`).join('')}</div></div></div>`
}
P.hostInfo = () => `<div class="card u" style="padding:18px 20px;display:grid;grid-template-columns:repeat(6,1fr);gap:14px">${[['OS', 'Ubuntu 22.04'], ['Kernel', '5.15.0-76'], ['Address', '10.0.1.12:22'], ['Region', 'us-east-1'], ['Uptime', '15 d 6 h', '#6EE7B7'], ['Sessions', '3']].map(([l, v, c]) => `<div><div style="color:var(--mut);font-size:12px">${l}</div><div style="font-size:14.5px;font-weight:600;margin-top:4px;${c ? `color:${c}` : ''}">${v}</div></div>`).join('')}</div>`
P.overviewFrame = () => P.shell('Hosts', `
  <div class="ph"><div><div class="crumb">Hosts${i('chevR', 'width:12px;height:12px')}<b>API Gateway</b></div><div style="display:flex;align-items:center;gap:12px">${P.os('ubuntu')}<h1>API Gateway</h1>${tag('Online', 'grn', 1)}${envTag('Production')}</div></div>
   <div class="acts"><span class="btn s">${i('folder')}Files</span><span class="btn s">${i('edit')}Edit</span><span class="btn p">${i('term')}Open terminal</span></div></div>
  <div style="display:flex;gap:4px;border-bottom:1px solid var(--line)">${['Overview', 'Performance', 'Storage', 'Network', 'Activity'].map((t, k) => `<span style="padding:10px 14px;font-weight:${k ? 500 : 600};color:${k ? 'var(--t2)' : '#fff'};${k ? '' : 'box-shadow:inset 0 -2px 0 var(--pri)'}">${t}</span>`).join('')}</div>
  ${P.hostInfo()}${P.cpu()}<div style="display:grid;grid-template-columns:1fr 1fr;gap:18px">${P.network()}${P.security()}</div>`)

// ---- keys: generate and export to a host ----
const steps = on => `<div class="steps">${['Configure', 'Review', 'Export', 'Connect'].map((s, k) => `${k ? '<span class="ln"></span>' : ''}<span class="s${k < on ? ' done' : k === on ? ' on' : ''}"><b>${k < on ? i('check', 'width:10px;height:10px;stroke-width:3') : k + 1}</b>${s}</span>`).join('')}</div>`
const kpanel = (title, on, body, foot) => `<div class="panel u" style="width:340px;height:600px;display:flex;flex-direction:column"><div class="ph2"><span class="ico" style="background:var(--pri-s);color:var(--pri)">${i('key')}</span><h2 style="font-size:15px">${title}</h2><span class="ib" style="margin-left:auto">${i('x')}</span></div>${steps(on)}<div style="padding:16px 18px;display:flex;flex-direction:column;gap:14px;flex:1">${body}</div><div style="display:flex;gap:10px;padding:14px 18px;border-top:1px solid var(--line)">${foot}</div></div>`
P.keyGen = () => kpanel('Generate key', 0, `<div class="fl">Label<div class="inp">ira-laptop</div></div><div class="fl">Key type${[['ED25519', 'Fast and secure. Recommended.', 1], ['ECDSA', 'Good for older servers.'], ['RSA 4096', 'Works everywhere.']].map(([t, d, on]) => `<div style="display:flex;gap:10px;align-items:flex-start;padding:11px 12px;border-radius:10px;box-shadow:inset 0 0 0 1px ${on ? 'var(--pri)' : 'var(--line2)'};${on ? 'background:var(--pri-s)' : ''}"><span style="width:16px;height:16px;border-radius:50%;box-shadow:inset 0 0 0 ${on ? 5 : 1.5}px ${on ? 'var(--pri)' : 'var(--line2)'};margin-top:1px;flex:none"></span><div><div style="color:var(--tx);font-weight:600">${t}</div><div style="color:var(--mut);font-size:12px;font-weight:400;margin-top:2px">${d}</div></div></div>`).join('')}</div><div class="fl">Passphrase<div class="inp ph">Optional</div></div>`, `<span class="btn g">Cancel</span><span class="btn p" style="margin-left:auto">Generate</span>`)
P.keyHost = () => kpanel('Export key', 2, `<div style="color:var(--t2);font-size:12.5px">Send <b style="color:var(--tx)">ira-laptop</b> to a host</div>${P.HOSTS.slice(0, 5).map(([n, os, ip], k) => `<div style="display:flex;align-items:center;gap:10px;padding:9px 10px;border-radius:10px;${k === 2 ? 'background:var(--pri-s);box-shadow:inset 0 0 0 1px var(--pri)' : 'box-shadow:inset 0 0 0 1px var(--line)'}">${P.os(os)}<div style="font-weight:600">${n}<div class="mono" style="font-size:11px;color:var(--mut);font-weight:400">${ip}</div></div>${k === 2 ? `<span style="margin-left:auto;color:var(--pri)">${i('check')}</span>` : ''}</div>`).join('')}`, `<span class="btn g">Back</span><span class="btn p" style="margin-left:auto">Export</span>`)
const ring = (pct, c, center) => `<div style="position:relative;width:170px;height:170px;margin:6px auto 0"><svg width="170" height="170" viewBox="0 0 170 170"><circle cx="85" cy="85" r="72" fill="none" stroke="#232737" stroke-width="8"/><circle cx="85" cy="85" r="72" fill="none" stroke="${c}" stroke-width="8" stroke-linecap="round" stroke-dasharray="${452 * pct} 452" transform="rotate(-90 85 85)"/></svg><div style="position:absolute;inset:0;display:grid;place-items:center">${center}</div></div>`
P.keyProgress = () => kpanel('Export key', 3, `${ring(.62, 'url(#pg)', `<div style="text-align:center"><div style="font-size:26px;font-weight:700">62%</div><div style="font-size:12px;color:var(--mut)">to DB-master</div></div>`).replace('<svg width="170"', '<svg width="170"><defs><linearGradient id="pg"><stop offset="0" stop-color="#8B5CF6"/><stop offset="1" stop-color="#38BDF8"/></linearGradient></defs></svg><svg style="position:absolute;inset:0" width="170"')}
  <div style="display:flex;flex-direction:column;gap:10px;margin-top:6px">${[['done', 'Connected to 10.0.2.5'], ['done', 'Signed in with password'], ['on', 'Adding key to authorized_keys'], ['', 'Testing key login']].map(([s, t]) => `<div style="display:flex;align-items:center;gap:10px;font-size:12.5px;color:${s ? 'var(--tx)' : 'var(--mut)'}"><span style="width:18px;height:18px;border-radius:50%;display:grid;place-items:center;flex:none;${s === 'done' ? 'background:var(--grn);color:#06221A' : s === 'on' ? 'box-shadow:inset 0 0 0 2px var(--pri)' : 'box-shadow:inset 0 0 0 1.5px var(--line2)'}">${s === 'done' ? i('check', 'width:10px;height:10px;stroke-width:3') : s === 'on' ? '<span style="width:6px;height:6px;border-radius:50%;background:var(--pri)"></span>' : ''}</span>${t}</div>`).join('')}</div>`, `<span class="btn g" style="margin-left:auto">Cancel</span>`)
P.keyDone = () => kpanel('Export key', 4, `${ring(1, 'var(--grn)', `<span style="width:64px;height:64px;border-radius:50%;background:var(--grn-s);display:grid;place-items:center;color:var(--grn)">${i('check', 'width:30px;height:30px;stroke-width:2.6')}</span>`)}
  <div style="text-align:center"><div style="font-size:16px;font-weight:650">Key added to DB-master</div><div style="color:var(--mut);font-size:12.5px;margin-top:6px;line-height:1.5">Next time, you connect without a password.</div></div>
  <div class="term" style="border-radius:10px;padding:10px 12px;font-size:11.5px;line-height:1.6;box-shadow:inset 0 0 0 1px var(--line)"><span class="c2">✓</span> ssh ira@10.0.2.5 <span class="c5"># key login works</span></div>`, `<span class="btn g">Done</span><span class="btn p" style="margin-left:auto">${i('term')}Connect now</span>`)

// ---- terminal ----
P.packages = () => `<div class="panel u" style="width:380px;height:660px;display:flex;flex-direction:column">
  <div class="ph2"><h2 style="font-size:15px">Saved commands</h2><span class="ib" style="margin-left:auto">${i('search')}</span><span class="ib">${i('x')}</span></div>
  <div style="padding:14px 16px 0"><span class="seg" style="width:100%"><span class="on" style="flex:1;justify-content:center">${i('box', 'width:14px;height:14px')}Packages</span><span style="flex:1;justify-content:center">${i('history', 'width:14px;height:14px')}History</span></span></div>
  <div style="padding:12px 8px;display:flex;flex-direction:column">
   <div style="display:flex;align-items:center;gap:10px;padding:10px 10px;font-weight:600">${i('box', 'color:var(--pri)')}devops-kit<span class="cnt" style="margin-left:auto;background:rgba(255,255,255,.06);color:var(--t2)">3</span>${i('chev', 'color:var(--mut)')}</div>
   ${[['Check network load', 1], ['Back up home folder'], ['Rotate logs']].map(([t, on]) => `<div style="margin-left:18px;padding:9px 12px;border-radius:9px;display:flex;align-items:center;gap:8px;${on ? 'background:var(--pri-s);color:#fff' : 'color:var(--t2)'}">${t}${on ? `<span class="btn sm p" style="margin-left:auto;height:26px">${i('play', 'width:12px;height:12px')}Run</span>` : ''}</div>`).join('')}
   ${['Git workflows', 'Server upkeep'].map(t => `<div style="display:flex;align-items:center;gap:10px;padding:12px 10px;border-top:1px solid var(--line);margin-top:6px;font-weight:600">${i('box', 'color:var(--mut)')}${t}<span class="cnt" style="margin-left:auto;background:rgba(255,255,255,.06);color:var(--t2)">3</span>${i('chevR', 'color:var(--mut)')}</div>`).join('')}
  </div>
  <div style="margin:4px 16px 0;border-radius:12px;box-shadow:inset 0 0 0 1px var(--line);overflow:hidden"><div style="display:flex;align-items:center;padding:9px 12px;border-bottom:1px solid var(--line);font-size:12px;color:var(--t2)"><span class="mono">check-network-load.sh</span><span style="margin-left:auto">${i('copy', 'width:14px;height:14px')}</span></div>
   <div class="term" style="padding:10px 12px;font-size:11.5px;line-height:1.65"><span class="c5">#!/usr/bin/env bash</span><br>set -euo pipefail<br><span class="c6">IFACE</span>=<span class="c2">"eth0"</span><br>rx=$(<span class="c1">cat</span> /sys/class/net/$IFACE/statistics/rx_bytes)<br><span class="c1">sleep</span> 1<br><span class="c1">echo</span> <span class="c2">"RX: $(( (now-rx)/1024 )) KB/s"</span></div></div>
  <div style="margin-top:auto;padding:14px 16px;border-top:1px solid var(--line);display:flex;align-items:center;gap:10px;font-size:12.5px;color:var(--t2)"><span class="tg on"></span>Autocomplete<span class="btn sm s" style="margin-left:auto">${i('spark', 'color:var(--cy)')}Ask AI</span></div></div>`
P.askAI = () => `<div class="panel u" style="width:380px;height:660px;display:flex;flex-direction:column">
  <div class="ph2">${i('spark', 'color:var(--cy)')}<h2 style="font-size:15px">Ask AI</h2><span class="ib" style="margin-left:auto">${i('x')}</span></div>
  <div style="padding:16px;display:flex;flex-direction:column;gap:14px;flex:1">
   <div style="align-self:flex-end;max-width:84%;padding:10px 14px;border-radius:14px 14px 4px 14px;background:var(--pri-s);box-shadow:inset 0 0 0 1px rgba(139,92,246,.4)">How do I find all .log files bigger than 100 MB?</div>
   <div style="display:flex;gap:10px"><span class="ico" style="background:var(--cy-s);color:var(--cy);width:26px;height:26px;flex:none">${i('spark', 'width:14px;height:14px')}</span><div style="color:var(--t2);line-height:1.6">Use <span class="mono" style="color:var(--tx)">find</span> with a size filter:
    <div class="term" style="margin:10px 0;border-radius:10px;padding:10px 12px;font-size:11.5px;box-shadow:inset 0 0 0 1px var(--line);display:flex;align-items:center"><span><span class="c1">find</span> /var/log -name <span class="c2">"*.log"</span> -size +100M</span></div>
    <div style="display:flex;gap:8px"><span class="btn sm p">${i('play', 'width:12px;height:12px')}Run in terminal</span><span class="btn sm s">${i('copy')}Copy</span></div>
    <div style="margin-top:12px">Add <span class="mono" style="color:var(--tx)">-exec ls -lh {} \\;</span> to see each file's size.</div></div></div></div>
  <div style="padding:14px 16px;border-top:1px solid var(--line)"><div class="inp" style="border-radius:12px;color:var(--mut)">Ask about a command<span class="sfx"><span class="ib" style="width:28px;height:28px;background:var(--pri);color:#fff;border-radius:8px">${i('send', 'width:14px;height:14px')}</span></span></div></div></div>`
P.termFrame = () => P.shell('Terminal', `<div style="display:flex;gap:18px;align-items:stretch;margin:-26px -28px -32px">
  <div style="flex:1;min-width:0;display:flex;flex-direction:column"><div style="display:flex;align-items:center;gap:8px;padding:10px 16px;border-bottom:1px solid var(--line)">${P.os('ubuntu')}<b>API Gateway</b><span class="mono" style="color:var(--mut);font-size:12px">ira@10.0.1.12</span>${tag('Connected', 'grn', 1)}</div>
   <div class="term" style="flex:1;padding:18px 22px;min-height:620px">
    <span class="c5">Last login: Fri Oct 10 08:45 from 10.0.0.2</span><br><span class="c2">ira@api-gateway</span>:<span class="c1">~</span>$ uptime<br>&nbsp;08:46:12 up 15 days, 6:02, 3 users, load average: 1.02, 0.88, 0.95<br>
    <span class="c2">ira@api-gateway</span>:<span class="c1">~</span>$ df -h /<br>Filesystem&nbsp;&nbsp;Size&nbsp;&nbsp;Used&nbsp;Avail&nbsp;Use%&nbsp;Mounted on<br>/dev/sda1&nbsp;&nbsp;&nbsp;&nbsp;80G&nbsp;&nbsp;&nbsp;69G&nbsp;&nbsp;&nbsp;11G&nbsp;&nbsp;<span class="c3">86%</span>&nbsp;/<br>
    <span class="c2">ira@api-gateway</span>:<span class="c1">~</span>$ ./check-network-load.sh<br><span class="c6">RX:</span> 1126 KB/s&nbsp;&nbsp;<span class="c6">TX:</span> 1638 KB/s<br><span class="c6">Peak:</span> 2.4 MB/s at 08:31<br>
    <span class="c2">ira@api-gateway</span>:<span class="c1">~</span>$ sudo systemctl status nginx<br><span class="c2">●</span> nginx.service - A high performance web server<br>&nbsp;&nbsp;&nbsp;Active: <span class="c2">active (running)</span> since Wed 2025-09-24<br>
    <span class="c2">ira@api-gateway</span>:<span class="c1">~</span>$ <span style="display:inline-block;width:8px;height:16px;background:#A9BCFF;vertical-align:-3px"></span></div></div>
  <div style="padding:16px 16px 16px 0">${P.packages()}</div></div>`)

// ---- sessions ----
const SESS = [['Ira Sen', 'ira@platform.dev', 'ubuntu', '10.0.1.12', 'MacBook Pro', 'Bengaluru, IN', '2 h 14 m', 'ED25519'], ['Dev Malhotra', 'dev@platform.dev', 'arch', '10.0.1.24', 'ThinkPad X1', 'Pune, IN', '48 m', 'RSA 4096'], ['Sara Thomas', 'sara@platform.dev', 'fedora', '10.0.2.5', 'Pixel 8', 'Kochi, IN', '12 m', 'ED25519'], ['Arjun Rao', 'arjun@platform.dev', 'debian', '10.0.3.18', 'Ubuntu desktop', 'Hyderabad, IN', '5 h 02 m', 'ECDSA'], ['Neha Kulkarni', 'neha@platform.dev', 'ubuntu', '10.0.0.2', 'MacBook Air', 'Mumbai, IN', '1 h 37 m', 'ED25519']]
P.sessionsCard = () => `<div class="card u" style="overflow:hidden;background:#0C0D13"><div class="ch"><span class="ico" style="background:var(--grn-s);color:var(--grn)">${i('users')}</span><h3>Active sessions</h3><span class="cnt" style="background:var(--grn-s);color:var(--grn)">5</span><span class="seg" style="margin-left:auto"><span class="on">All hosts</span><span>Production</span></span></div>
  <table class="tbl"><tr><th>User</th><th>Host</th><th>Device</th><th>Location</th><th>Time</th><th>Key</th><th></th></tr>${SESS.map(([n, e, os, ip, dev, loc, t, k]) => `<tr><td><div class="who">${av(n)}<div style="font-weight:600">${n}<small>${e}</small></div></div></td><td><div class="who" style="gap:8px">${P.os(os).replace('class="os"', 'class="os" style="width:26px;height:26px"')}<span class="mono" style="font-size:12px">${ip}</span></div></td><td style="color:var(--t2)">${dev}</td><td style="color:var(--t2)">${loc}</td><td>${t}</td><td>${tag(k, 'pri')}</td><td class="r"><span class="btn sm s" style="color:#FCA5A5">End</span></td></tr>`).join('')}</table></div>`

// ---- key export, rebuilt from her original panels (445 x 740) with small tweaks ----
const kkey = '<svg viewBox="0 0 24 24" width="30" height="30"><circle cx="8" cy="15" r="5" fill="#38BDF8"/><circle cx="8" cy="15" r="1.8" fill="#0F1018"/><path d="M11.5 11.5 20 3M16.5 6.5l2.5 2.5M14 9l2 2" stroke="#38BDF8" stroke-width="3" stroke-linecap="round"/></svg>'
const ksteps = (names, on) => `<div style="margin:0 18px;border-radius:12px;box-shadow:inset 0 0 0 1px var(--line);padding:14px 40px 12px;display:flex;align-items:flex-start">${names.map((n, k) => `${k ? '<span style="flex:1;height:1.5px;background:var(--line2);margin-top:10px"></span>' : ''}<span style="display:flex;flex-direction:column;align-items:center;gap:7px;font-size:12px;color:${k <= on ? 'var(--tx)' : 'var(--mut)'};width:0;overflow:visible;white-space:nowrap"><span style="width:21px;height:21px;border-radius:50%;display:grid;place-items:center;flex:none;${k < on ? 'background:#22C55E;color:#04210F' : k === on ? 'box-shadow:inset 0 0 0 2px var(--pri)' : 'box-shadow:inset 0 0 0 1.5px var(--line2);color:var(--mut);font-size:10px'}">${k < on ? i('check', 'width:11px;height:11px;stroke-width:3.2') : k === on ? '<span style="width:9px;height:9px;border-radius:50%;background:var(--pri)"></span>' : k + 1}</span>${n}</span>`).join('')}</div>`
const kp = (title, inner, foot) => `<div class="panel u" style="width:445px;height:740px;display:flex;flex-direction:column;border-radius:20px">
  <div style="display:flex;align-items:center;gap:12px;padding:22px 24px;border-bottom:1px solid var(--line)">${kkey}<h2 style="font-size:20px">${title}</h2>${i('chev', 'color:var(--t2)')}<span style="margin-left:auto;color:var(--t2)">${i('x', 'width:22px;height:22px')}</span></div>
  <div style="padding:22px 0 0;display:flex;flex-direction:column;gap:20px;flex:1">${inner}</div>
  ${foot ? `<div style="display:flex;align-items:center;padding:18px 24px;border-top:1px solid var(--line)">${foot}</div>` : ''}</div>`
P.kSelect = () => `<div class="panel u" style="width:581px;border-radius:20px">
  <div style="display:flex;align-items:center;gap:12px;padding:20px 24px;border-bottom:1px solid var(--line)"><span style="color:#C4B5FD">${i('server', 'width:24px;height:24px')}</span><h2 style="font-size:19px">Select host</h2><span style="margin-left:auto;color:var(--t2)">${i('x', 'width:22px;height:22px')}</span></div>
  <div style="padding:20px 24px;display:flex;flex-direction:column;gap:16px"><div style="display:flex;gap:10px"><div class="inp" style="flex:1;color:var(--mut)">${i('search')}Search hosts</div><span class="btn s">${i('plus')}New host</span></div>
   <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px">${P.HOSTS.slice(0, 6).map(([n, os, ip], k) => `<div style="display:flex;align-items:center;gap:10px;padding:10px 12px;border-radius:10px;${k === 2 ? 'background:var(--pri-s);box-shadow:inset 0 0 0 1px var(--pri)' : 'background:var(--card2)'}">${P.os(os)}<div style="font-weight:600">${n}<div class="mono" style="font-size:11px;color:var(--mut);font-weight:400">${ip}</div></div><span style="margin-left:auto;color:${k === 2 ? 'var(--pri)' : 'var(--mut)'}">${i(k === 2 ? 'check' : 'plus')}</span></div>`).join('')}</div></div>
  <div style="display:flex;align-items:center;padding:16px 24px;border-top:1px solid var(--line)"><span class="btn g">Cancel</span><span class="btn p" style="margin-left:auto;height:42px;padding:0 20px">Select host</span></div></div>`
P.kExport = () => kp('Export key', `${ksteps(['Configure', 'Review', 'Export', 'Connect'], 2)}
  <div style="padding:0 18px;display:flex;flex-direction:column;gap:16px">
   <div style="display:flex;gap:10px"><div class="inp" style="flex:1;height:52px;background:var(--card2)">${P.os('fedora')}<div style="font-weight:600">DB-master<div class="mono" style="font-size:11px;color:var(--mut);font-weight:400">10.0.2.5</div></div><span class="sfx">${i('chev')}</span></div><span class="btn p" style="width:52px;height:52px;padding:0;justify-content:center">${i('plus', 'width:22px;height:22px')}</span></div>
   <div class="fl">Export location<div class="inp mono" style="font-size:13px">~/.ssh</div></div>
   <div class="fl">Filename<div class="inp mono" style="font-size:13px">authorized_keys</div></div>
   <div class="fl">Export script<div class="term" style="border-radius:10px;padding:12px 14px;font-size:12px;line-height:1.7;box-shadow:inset 0 0 0 1px var(--line)"><span class="c5"># Copy ira-laptop to DB-master</span><br><span class="c1">echo</span> <span class="c2">"Connecting to 10.0.2.5..."</span><br><span class="c1">ssh-copy-id</span> -i ~/.ssh/ira-laptop.pub ira@10.0.2.5<br><span class="c1">echo</span> <span class="c2">"Key exported"</span></div></div></div>`,
  `<span class="btn g">Cancel</span><span class="btn p" style="margin-left:auto;height:44px;padding:0 26px;font-size:14px">Export</span>`)
const tickRing = (c, frac) => { let t = ''; for (let k = 0; k < 72; k++) { const a = k / 72 * Math.PI * 2, on = k / 72 < frac; t += `<line x1="${95 + 74 * Math.cos(a)}" y1="${95 + 74 * Math.sin(a)}" x2="${95 + 84 * Math.cos(a)}" y2="${95 + 84 * Math.sin(a)}" stroke="${on ? c : '#2A2E3D'}" stroke-width="3" stroke-linecap="round"/>` } return t }
P.kDone = () => kp('Export key', `${ksteps(['Configure', 'Review', 'Export', 'Connect'], 4)}
  <div style="position:relative;width:250px;height:190px;margin:26px auto 0"><svg width="190" height="190" style="position:absolute;left:30px;top:0"><circle cx="95" cy="95" r="92" fill="none" stroke="#1E2230"/>${tickRing('#5EEAD4', 1)}</svg>
   <span style="position:absolute;left:107px;top:77px;width:36px;height:36px;border-radius:50%;background:linear-gradient(180deg,#34D399,#10B981);display:grid;place-items:center;color:#04210F">${i('check', 'width:18px;height:18px;stroke-width:3')}</span>
   <span style="position:absolute;left:4px;top:76px;width:40px;height:40px;border-radius:50%;background:#38BDF8;display:grid;place-items:center;color:#06222F">${i('key', 'width:18px;height:18px;stroke-width:2.2')}</span>
   <span style="position:absolute;right:4px;top:76px;width:40px;height:40px;border-radius:50%;background:#C084FC;display:grid;place-items:center;color:#2A0A40">${i('server', 'width:18px;height:18px;stroke-width:2.2')}</span></div>
  <div style="text-align:center"><div style="font-size:19px;font-weight:650;color:#34D399">Connection successful</div><div style="color:var(--t2);margin-top:8px;line-height:1.55">ira-laptop is on DB-master.<br>You can now log in without a password.</div></div>
  <div style="margin:0 18px;border-radius:12px;box-shadow:inset 0 0 0 1px var(--line);padding:12px 16px;display:flex;flex-direction:column;gap:10px">${['Connected to 10.0.2.5', 'Key added to authorized_keys', 'Key login tested'].map(t => `<div style="display:flex;align-items:center;gap:10px;color:var(--t2)"><span style="color:#34D399">${i('check', 'width:14px;height:14px;stroke-width:2.8')}</span>${t}</div>`).join('')}</div>`,
  `<span class="btn g">Done</span><span class="btn p" style="margin-left:auto;height:44px;padding:0 22px;font-size:14px">${i('term')}Open terminal</span>`)
})()
