// SSH client: her original screens rebuilt as they are in Figma (layout, sidebar, tabs, buttons), with modern colours and
// small fixes only: real host names and IPs, rounder corners, cleaner borders. Every name and number is sample data.
(function(){
const i = P.i, os = P.os
const W = 1280
const C = { bg: '#121216', rail: '#0D0D10', bar: '#0D0D10', card: '#18181D', card2: '#212128', line: '#2A2A31', t2: '#A1A1AA', mut: '#71717A', vio: '#8B5CF6' }
P.W = W
const vbtn = (h = 36) => `<span style="display:inline-flex;height:${h}px;border-radius:9px;overflow:hidden;background:linear-gradient(180deg,#9655FF,#7328F0);box-shadow:0 8px 20px -10px rgba(124,58,237,.9)"><span style="width:${h + 10}px;display:grid;place-items:center;color:#fff">${i('plus', 'width:20px;height:20px')}</span><span style="width:28px;display:grid;place-items:center;color:#fff;border-left:1px solid rgba(255,255,255,.25)">${i('chev', 'width:14px;height:14px')}</span></span>`
const RAIL = [['server', 'Hosts'], ['term', 'Terminal'], ['ports', 'Port<br>Mapping'], ['folder', 'SFTP'], ['grid', 'More']]
// The app frame: tab strip, icon rail with labels, top bar with search, view toggle, vault and the + button.
P.frame = (active, content, { tab = 'Tab 1', h = 832, plus = true } = {}) => `<div class="u" style="width:${W}px;height:${h}px;background:${C.bg};position:relative;display:flex;flex-direction:column;overflow:hidden">
  <div style="height:36px;display:flex;background:${C.bar};border-bottom:1px solid ${C.line}"><span style="width:94px;display:grid;place-items:center;border-right:1px solid ${C.line};color:${C.vio}">${i('server', 'width:0;height:0')}<svg viewBox="0 0 24 24" width="17" height="17" fill="${C.vio}"><path d="M3 11 12 3l9 8v10h-6v-6H9v6H3z"/></svg></span>
   <span style="display:flex;align-items:center;gap:28px;padding:0 14px;font-size:12.5px;color:#fff;background:${C.bg};border-right:1px solid ${C.line}">${tab}<span style="color:${C.mut}">${i('x', 'width:12px;height:12px')}</span></span></div>
  <div style="flex:1;display:flex;min-height:0">
   <div style="width:94px;flex:none;background:${C.rail};border-right:1px solid ${C.line};display:flex;flex-direction:column;align-items:center;padding:0 0 22px">
    <div style="height:62px;width:100%;border-bottom:1px solid ${C.line}"></div>
    <div style="margin:auto 0;display:flex;flex-direction:column;gap:22px;align-items:center">${RAIL.map(([ic, n]) => { const on = n.replace('<br>', ' ') === active; return `<div style="display:flex;flex-direction:column;align-items:center;gap:6px;font-size:12.5px;text-align:center;line-height:1.3;color:${on ? '#fff' : C.t2};font-weight:${on ? 600 : 400}"><span style="width:38px;height:38px;border-radius:50%;display:grid;place-items:center;${on ? 'background:rgba(139,92,246,.22);color:#C4B5FD' : ''}">${i(ic, 'width:18px;height:18px')}</span>${n}</div>` }).join('')}</div>
    <div style="display:flex;flex-direction:column;gap:20px;color:${C.t2}">${i('bell', 'width:19px;height:19px')}${i('gear', 'width:19px;height:19px')}</div></div>
   <div style="flex:1;min-width:0;display:flex;flex-direction:column">
    <div style="height:62px;flex:none;display:flex;align-items:center;gap:18px;padding:0 28px 0 24px;border-bottom:1px solid ${C.line}"><span style="color:${C.t2}">${i('arrowL', 'width:20px;height:20px')}</span><span style="color:${C.t2}">${i('arrowR', 'width:20px;height:20px')}</span>
     <div style="width:312px;height:32px;border-radius:8px;background:${C.card};box-shadow:inset 0 0 0 1px ${C.line};display:flex;align-items:center;gap:8px;padding:0 12px;color:${C.mut};font-size:13px">${i('search', 'width:13px;height:13px')}Search</div>
     <span style="margin-left:auto;display:inline-flex;gap:2px;padding:2px;border-radius:8px;background:${C.card}"><span style="width:30px;height:28px;border-radius:6px;display:grid;place-items:center;background:${C.card2};color:#fff">${i('grid', 'width:15px;height:15px')}</span><span style="width:30px;height:28px;display:grid;place-items:center;color:${C.t2}">${i('list', 'width:15px;height:15px')}</span></span>
     <span style="color:${C.t2}">${i('list', 'width:18px;height:18px')}</span>
     <span style="height:36px;border-radius:9px;box-shadow:inset 0 0 0 1px ${C.line};background:${C.card};display:flex;align-items:center;gap:9px;padding:0 12px;font-size:13.5px;font-weight:500"><span style="width:20px;height:20px;border-radius:50%;background:#38BDF8;color:#05202C;display:grid;place-items:center;font-size:11px;font-weight:700">A</span>Personal Vault<span style="color:${C.t2}">${i('chev', 'width:14px;height:14px')}</span></span>
     ${plus ? vbtn() : ''}</div>
    <div style="flex:1;min-height:0;position:relative">${content}</div></div></div></div>`

// ---- hosts: her card grid ----
const HOSTS = [['API Gateway', 'ubuntu', '10.0.1.12'], ['Staging-server', 'fedora', '10.0.3.18'], ['Test-app-01', 'arch', '10.0.4.31'], ['Test-app-02', 'arch', '10.0.4.32'], ['Prod-server-1', 'fedora', '10.0.2.5'], ['Prod-server-2', 'debian', '10.0.2.6'], ['Jump-server', 'ubuntu', '10.0.0.2'], ['Cloud-instance-01', 'arch', '10.0.1.24']]
P.HOSTS2 = HOSTS
P.hostCard = ([n, o, ip], w = 305) => `<div class="u" style="width:${w}px;border-radius:14px;background:${C.card};box-shadow:inset 0 0 0 1px ${C.line}">
  <div style="display:flex;align-items:center;gap:14px;padding:16px 16px 18px"><span style="width:48px;height:48px;border-radius:12px;background:${C.card2};display:grid;place-items:center">${os(o).replace('class="os"', 'class="os" style="background:none;box-shadow:none;width:28px;height:28px"')}</span><div><div style="font-size:15.5px;font-weight:600;display:flex;align-items:center;gap:7px">${n}<span class="dot" style="background:#34D399;width:7px;height:7px"></span></div><div class="mono" style="font-size:12.5px;color:${C.t2};margin-top:3px">${ip}</div></div><span style="margin-left:auto;align-self:flex-start;color:${C.t2}">${i('more', 'width:18px;height:18px;transform:rotate(90deg)')}</span></div>
  <div style="position:relative;border-top:1px solid ${C.line}"><span style="position:absolute;left:50%;top:-9px;margin-left:-9px;width:18px;height:18px;border-radius:50%;background:${C.card2};box-shadow:inset 0 0 0 1px ${C.line};display:grid;place-items:center;color:${C.t2}">${i('chev', 'width:11px;height:11px')}</span></div>
  <div style="display:flex;align-items:center;gap:6px;padding:12px 16px">${['chart', 'term', 'file'].map(ic => `<span style="width:30px;height:28px;border-radius:7px;background:${C.card2};display:grid;place-items:center;color:${C.t2}">${i(ic, 'width:13px;height:13px')}</span>`).join('')}<span style="margin-left:auto;height:30px;padding:0 18px;border-radius:8px;background:${C.card2};box-shadow:inset 0 0 0 1px ${C.line};display:grid;place-items:center;font-size:12.5px;font-weight:600">Connect</span></div></div>`
const filters = `<span style="display:inline-flex;gap:2px;padding:4px;border-radius:10px;background:${C.card};box-shadow:inset 0 0 0 1px ${C.line};font-size:13.5px">${[['list', 'All', 1], ['users', 'Group'], ['link2', 'Serial'], ['dot', 'Connected'], ['star', 'Favourite']].map(([ic, t, on]) => `<span style="height:32px;padding:0 12px;border-radius:7px;display:flex;align-items:center;gap:7px;${on ? `background:${C.card2};color:#fff` : `color:${C.t2}`}">${ic === 'dot' ? '<span class="dot" style="background:#34D399"></span>' : ic === 'star' ? '<span style="color:#FBBF24">★</span>' : i(ic === 'link2' ? 'ports' : ic, 'width:14px;height:14px')}${t}</span>`).join('')}</span>`
P.newHost2 = () => `<div class="u" style="width:445px;height:100%;background:${C.card};border-left:1px solid ${C.line};display:flex;flex-direction:column">
  <div style="display:flex;align-items:center;gap:12px;padding:22px 24px;border-bottom:1px solid ${C.line}"><span style="color:#C4B5FD">${i('server', 'width:26px;height:26px')}</span><span style="font-size:19px;font-weight:600">New Host</span>${i('chev', `color:${C.t2}`)}<span style="margin-left:auto;color:${C.t2};display:flex;gap:18px">${i('send', 'width:18px;height:18px')}${i('x', 'width:22px;height:22px')}</span></div>
  <div style="padding:20px 24px 0"><span style="display:flex;padding:4px;border-radius:10px;background:${C.bg};box-shadow:inset 0 0 0 1px ${C.line};font-size:12.5px">${['Connection', 'Authentication', 'Advanced', 'Appearance'].map((t, k) => `<span style="flex:1;height:30px;border-radius:7px;display:grid;place-items:center;${k ? `color:${C.t2}` : `background:${C.card2};color:#fff;font-weight:600`}">${t}</span>`).join('')}</span></div>
  <div style="padding:20px 24px;display:flex;flex-direction:column;gap:18px;font-size:12.5px;color:${C.t2}">
   ${[['Host Address', 'server', '10.0.5.20', 1], ['Label', 'tag', 'Billing-worker']].map(([l, ic, v, foc]) => `<div style="display:flex;flex-direction:column;gap:8px">${l}<div style="height:42px;border-radius:10px;background:${C.bg};box-shadow:inset 0 0 0 1px ${foc ? C.vio : C.line}${foc ? ',0 0 0 3px rgba(139,92,246,.2)' : ''};display:flex;align-items:center;gap:10px;padding:0 14px;color:#fff;font-size:13.5px">${i(ic === 'tag' ? 'edit' : ic, `width:15px;height:15px;color:${C.mut}`)}<span class="${ic === 'server' ? 'mono' : ''}">${v}</span></div></div>`).join('')}
   <div style="display:flex;flex-direction:column;gap:8px">SSH Port<div style="width:180px;height:42px;border-radius:10px;background:${C.bg};box-shadow:inset 0 0 0 1px ${C.line};display:flex;align-items:center;padding:0 14px;color:#fff" class="mono">22</div></div>
   <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px">${[['Tags', 'worker'], ['Group', 'Production']].map(([l, v]) => `<div style="display:flex;flex-direction:column;gap:8px">${l}<div style="height:42px;border-radius:10px;background:${C.bg};box-shadow:inset 0 0 0 1px ${C.line};display:flex;align-items:center;gap:8px;padding:0 12px;color:#fff;font-size:13px"><span class="tag t-pri">${v}</span><span style="margin-left:auto;color:${C.t2}">${i('chev')}</span></div></div>`).join('')}</div>
   <div style="display:flex;flex-direction:column;gap:8px">Vault<div style="height:42px;border-radius:10px;background:${C.bg};box-shadow:inset 0 0 0 1px ${C.line};display:flex;align-items:center;gap:10px;padding:0 14px;color:#fff;font-size:13.5px"><span style="width:20px;height:20px;border-radius:50%;background:#38BDF8;color:#05202C;display:grid;place-items:center;font-size:11px;font-weight:700">A</span>Personal Vault<span style="margin-left:auto;color:${C.t2}">${i('chev')}</span></div></div></div>
  <div style="margin-top:auto;display:flex;align-items:center;padding:18px 24px;border-top:1px solid ${C.line}"><span style="font-weight:600;color:#fff;padding:0 18px">Cancel</span><span class="btn p" style="margin-left:auto;height:44px;padding:0 34px;font-size:14px">Connect</span></div></div>`
P.hostsFrame2 = () => P.frame('Hosts', `<div style="display:flex;height:100%"><div style="flex:1;padding:36px 0 0 66px;overflow:hidden">
  <div style="display:flex;align-items:center;gap:26px;margin-bottom:24px"><span style="font-size:24px;font-weight:650">Hosts</span>${filters}</div>
  <div style="display:grid;grid-template-columns:305px 305px;gap:24px">${HOSTS.map(h => P.hostCard(h)).join('')}</div></div>${P.newHost2()}</div>`)

// ---- host page: her Overview, Performance and Network tabs ----
const hostHead = (tab) => `<div style="display:flex;align-items:center;gap:12px;margin-bottom:24px">${os('ubuntu').replace('class="os"', 'class="os" style="background:none;box-shadow:none;width:34px;height:34px"')}<span style="font-size:25px;font-weight:650">API Gateway</span>
  <span style="margin-left:auto;display:inline-flex;padding:4px;border-radius:10px;background:${C.card};box-shadow:inset 0 0 0 1px ${C.line};font-size:14px">${[['chart', 'Stats', '#C4B5FD', 1], ['folder', 'File Explorer', '#38BDF8'], ['term', 'Terminal ↗', '#34D399'], ['edit', 'Edit Host', '#FBBF24']].map(([ic, t, c, on]) => `<span style="height:34px;padding:0 16px;border-radius:7px;display:flex;align-items:center;gap:8px;font-weight:500;${on ? `background:${C.card2}` : ''}">${i(ic, `width:16px;height:16px;color:${c}`)}${t}</span>`).join('')}</span></div>
  <div style="border-radius:14px 14px 0 0;background:${C.card};display:flex;box-shadow:inset 0 -1px 0 ${C.line}">${['Overview', 'Performance', 'Storage', 'Network', 'Activity'].map(t => `<span style="flex:1;height:50px;display:grid;place-items:center;font-size:15px;${t === tab ? 'color:#fff;font-weight:600;box-shadow:inset 0 -2px 0 #A78BFA' : `color:${C.t2}`}">${t}</span>`).join('')}</div>`
const box = (ic, c, title, inner, st = '') => `<div class="u" style="border-radius:14px;box-shadow:inset 0 0 0 1px ${C.line};background:${C.card};padding:22px 26px;${st}"><div style="display:flex;align-items:center;gap:10px;font-size:15.5px;font-weight:600;margin-bottom:18px">${ic ? i(ic, `width:18px;height:18px;color:${c}`) : ''}${title}</div>${inner}</div>`
const kv = (l, v, c = '#fff') => `<div><div style="color:${C.t2};font-size:13px">${l}</div><div style="font-size:15.5px;font-weight:500;margin-top:6px;color:${c}">${v}</div></div>`
P.security2 = (st) => box(null, null, 'Security Insights', [['INFO', 'SSH uses key-based login'], ['INFO', 'Firewall on, 3 rules'], ['WARN', 'Disk /dev/sda1 is 86% full'], ['INFO', 'All system packages up to date'], ['INFO', 'Last login: ira from 10.0.0.2 at 08:45']].map(([b, t], k) => `<div style="display:flex;align-items:center;gap:22px;padding:12px 0;${k ? `border-top:1px solid ${C.line}` : ''}"><span style="width:66px;height:28px;border-radius:6px;display:grid;place-items:center;font-size:12.5px;font-weight:600;letter-spacing:.04em;${b === 'WARN' ? 'background:rgba(251,191,36,.12);color:#FBBF24' : 'background:rgba(56,189,248,.12);color:#38BDF8'}">${b}</span><span style="font-size:14px">${t}</span></div>`).join(''), st)
P.hostInfo2 = (st) => box('info', '#A7ABBE', 'Host Info', `<div style="display:grid;grid-template-columns:repeat(4,1fr);row-gap:20px">${kv('OS', 'Ubuntu 22.04 LTS')}${kv('Kernel', '5.15.0-76')}${kv('IP Address', '10.0.1.12')}${kv('Port', '22')}${kv('Last Reboot', '24 Sep 2025, 08:30')}${kv('Active Sessions', '3')}${kv('Uptime', '15 days, 6 hours', '#34D399')}<div><div style="color:${C.t2};font-size:13px">Status</div><div style="font-size:15.5px;font-weight:500;margin-top:6px;display:flex;align-items:center;gap:8px"><span class="dot" style="background:#34D399"></span>Connected</div></div></div>`, st)
P.netCard2 = (st) => box('globe', '#A78BFA', 'Eth0', `<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:12px">${[['IP Address', '10.0.1.12'], ['MAC Address', '00:1c:42:2b:60:5c'], ['Total RX / TX', '8.7 GB / 6.2 GB']].map(([l, v]) => `<div style="border-radius:10px;box-shadow:inset 0 0 0 1px ${C.line};padding:12px 14px"><div style="color:${C.t2};font-size:12.5px">${l}</div><div style="margin-top:6px;font-size:14.5px">${v}</div></div>`).join('')}</div>
  <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px">${[['down', 'Download', 'RX rate', '1.1', '#C4B5FD', [3, 3, 3, 3, 4, 4, 5, 5, 5, 4, 6, 6, 7, 5, 5, 6, 9, 9, 4]], ['up', 'Upload', 'TX rate', '1.6', '#5EEAD4', [3, 3, 3, 3, 4, 5, 5, 6, 6, 5, 5, 7, 7, 8, 5, 5, 7, 10, 10, 4]]].map(([ic, t, s, v, c, d]) => `<div style="border-radius:12px;box-shadow:inset 0 0 0 1px ${C.line};padding:16px 18px"><div style="display:flex;gap:12px;align-items:center"><span style="width:38px;height:38px;border-radius:9px;background:${C.card2};display:grid;place-items:center;color:${C.t2}">${i(ic, 'width:16px;height:16px')}</span><div><div style="font-size:14.5px">${t}</div><div style="font-size:11.5px;color:${C.mut}">${s}</div></div></div><div style="margin:14px 0 4px"><span style="font-size:24px;font-weight:650;color:${c}">${v}</span><span style="color:${C.t2};font-size:13px"> MB/s</span></div><div style="color:${C.t2};font-size:12.5px">Total: 12.35 GB</div><div style="display:flex;align-items:flex-end;gap:4px;height:34px;margin-top:12px">${d.map(h => `<span style="flex:1;height:${h * 3.2}px;border-radius:3px 3px 1px 1px;background:${c}"></span>`).join('')}</div></div>`).join('')}</div>`, st)
P.overviewFrame2 = () => P.frame('Hosts', `<div style="padding:44px 100px 0 100px">${hostHead('Overview')}<div style="background:${C.card};border-radius:0 0 14px 14px;padding:24px 34px 30px;display:flex;flex-direction:column;gap:16px;box-shadow:inset 0 0 0 1px ${C.line}">
  ${P.hostInfo2()}${box('file', '#38BDF8', 'System Metadata', `<div style="display:grid;grid-template-columns:repeat(3,1fr)">${kv('Environment', 'Production')}${kv('Region', 'us-east-1 (Virginia)')}${kv('Owner', 'Platform team')}</div>`)}${P.security2()}</div></div>`, { h: 1060 })

// ---- terminal: her terminal with the settings panel ----
P.termPanel = (mode) => `<div class="u" style="width:383px;height:${mode === 'dock' ? '100%' : '796px'};background:${C.card};border-radius:${mode === 'dock' ? 0 : 18}px;${mode === 'dock' ? `border-left:1px solid ${C.line}` : `box-shadow:inset 0 0 0 1px ${C.line}`};display:flex;flex-direction:column;position:relative">
  <div style="display:flex;align-items:center;padding:20px 22px;border-bottom:1px solid ${C.line}"><span style="font-size:16px;font-weight:600">Terminal Settings</span><span style="margin-left:auto;display:flex;gap:18px;color:${C.t2}">${i('spark', 'width:18px;height:18px')}${i('x', 'width:20px;height:20px')}</span></div>
  <div style="display:flex;align-items:center;gap:10px;padding:22px;border-bottom:1px solid ${C.line};font-size:14px"><span style="color:#38BDF8">${i('spark', 'width:20px;height:20px')}</span>Autocomplete Commands<span style="margin-left:auto;width:44px;height:24px;border-radius:12px;background:#0EA5E9;position:relative"><span style="position:absolute;right:3px;top:3px;width:18px;height:18px;border-radius:50%;background:#fff"></span></span></div>
  <div style="display:flex;gap:10px;padding:18px 22px 12px"><span style="flex:1;display:flex;padding:4px;border-radius:10px;background:${C.card2}">${[['box', 'Packages', 1], ['history', 'History']].map(([ic, t, on]) => `<span style="flex:1;height:34px;border-radius:7px;display:flex;align-items:center;justify-content:center;gap:7px;font-size:14px;font-weight:500;${on ? 'background:linear-gradient(180deg,#5CC8FF,#2EA8F0);color:#03202E' : `color:${C.t2}`}">${i(ic, 'width:15px;height:15px')}${t}</span>`).join('')}</span><span style="width:42px;border-radius:10px;background:${C.card2};display:grid;place-items:center;color:${C.t2}">${i('search', 'width:16px;height:16px')}</span></div>
  ${mode === 'cmd' ? `<div style="padding:4px 22px 0"><span style="width:28px;height:28px;border-radius:7px;background:${C.card2};display:grid;place-items:center;color:${C.t2}">${i('arrowL', 'width:14px;height:14px')}</span>
    <div style="display:flex;align-items:center;margin:16px 0 12px"><span style="font-size:16px;font-weight:600">Check Network Load</span><span style="margin-left:auto;color:${C.t2};margin-right:14px">${i('copy', 'width:16px;height:16px')}</span><span style="height:28px;padding:0 14px;border-radius:7px;background:#0EA5E9;color:#03202E;font-weight:600;font-size:12.5px;display:flex;align-items:center;gap:5px">${i('play', 'width:11px;height:11px')}Run</span></div>
    <div class="term" style="border-radius:10px;box-shadow:inset 0 0 0 1px ${C.line};padding:14px 16px;font-size:12px;line-height:1.75"><span class="c5">#!/usr/bin/env bash</span><br><span class="c5"># Show live network load on eth0</span><br>set -euo pipefail<br><br><span class="c1">IFACE</span>=<span class="c2">"eth0"</span><br><span class="c1">LOG</span>=<span class="c2">"$HOME/.netload.log"</span><br><br>rx1=$(<span class="c1">cat</span> /sys/class/net/$IFACE/statistics/rx_bytes)<br><span class="c1">sleep</span> 1<br>rx2=$(<span class="c1">cat</span> /sys/class/net/$IFACE/statistics/rx_bytes)<br><br><span class="c1">echo</span> <span class="c2">"RX: $(( (rx2-rx1)/1024 )) KB/s"</span> | tee -a <span class="c2">"$LOG"</span></div></div>`
  : `<div style="padding:4px 22px 0"><span style="width:28px;height:28px;border-radius:7px;background:${C.card2};display:grid;place-items:center;color:${C.t2}">${i('arrowL', 'width:14px;height:14px')}</span></div>
    <div style="padding:10px 22px 0"><div style="display:flex;align-items:center;gap:10px;padding:12px 0;font-size:15px;font-weight:500">${i('box', `width:16px;height:16px;color:${C.t2}`)}devops-kit<span style="margin-left:auto;width:20px;height:20px;border-radius:50%;background:${C.card2};display:grid;place-items:center;font-size:11px;color:${C.t2}">3</span>${i('chev', `width:15px;height:15px;color:${C.t2};transform:rotate(180deg)`)}</div>
     <div style="margin-left:6px;padding-left:12px;border-left:1.5px solid ${C.line};display:flex;flex-direction:column">${['Check Network Load', 'Back Up Home Folder', 'Rotate Logs'].map((t, k) => `<div style="display:flex;align-items:center;padding:9px 6px;font-size:13.5px;border-radius:7px;${k === 0 ? `background:${C.card2}` : ''}">${t}<span style="margin-left:auto;color:${C.t2}">${i('chevR', 'width:14px;height:14px')}</span></div>`).join('')}</div>
     ${['Git Workflows', 'Server Management'].map(t => `<div style="display:flex;align-items:center;gap:10px;padding:16px 0;border-top:1px solid ${C.line};margin-top:12px;font-size:15px;font-weight:500">${i('box', `width:16px;height:16px;color:${C.t2}`)}${t}<span style="margin-left:auto;width:20px;height:20px;border-radius:50%;background:${C.card2};display:grid;place-items:center;font-size:11px;color:${C.t2}">3</span>${i('chevR', `width:15px;height:15px;color:${C.t2}`)}</div>`).join('')}</div>`}
  <span style="position:absolute;right:22px;bottom:22px;height:42px;padding:0 18px;border-radius:21px;background:linear-gradient(180deg,#5CC8FF,#2EA8F0);color:#03202E;font-weight:600;font-size:14px;display:flex;align-items:center;gap:7px;box-shadow:0 10px 24px -10px rgba(56,189,248,.8)">${i('spark', 'width:17px;height:17px')}Ask AI</span></div>`
P.askAI2 = () => `<div class="u" style="width:383px;height:796px;background:${C.card};border-radius:18px;box-shadow:inset 0 0 0 1px ${C.line};display:flex;flex-direction:column">
  <div style="display:flex;align-items:center;gap:12px;padding:20px 22px;border-bottom:1px solid ${C.line}"><span style="color:${C.t2}">${i('arrowL', 'width:18px;height:18px')}</span><span style="color:#A78BFA">${i('spark', 'width:20px;height:20px')}</span><span style="font-size:16px;font-weight:600">Ask AI</span><span style="margin-left:auto;color:${C.t2}">${i('x', 'width:20px;height:20px')}</span></div>
  <div style="padding:22px;display:flex;flex-direction:column;gap:22px;font-size:14px;line-height:1.6">
   <div style="display:flex;justify-content:flex-end;gap:10px;align-items:center"><span style="padding:10px 14px;border-radius:10px;background:${C.card2}">How do I find all .txt files in a folder?</span><span style="width:26px;height:26px;border-radius:50%;background:#38BDF8;color:#05202C;display:grid;place-items:center;font-size:12px;font-weight:700;flex:none">A</span></div>
   <div style="display:flex;gap:12px"><span style="color:#A78BFA;margin-top:2px">${i('spark', 'width:18px;height:18px')}</span><div style="color:#E4E6F0">Use the <span class="mono" style="color:#C4B5FD">find</span> command.<br><br>In this folder and its subfolders:<div class="term" style="margin:8px 0 14px;border-radius:9px;padding:9px 12px;font-size:12px;box-shadow:inset 0 0 0 1px ${C.line}"><span class="c1">find</span> . -name <span class="c2">"*.txt"</span></div>In one folder only:<div class="term" style="margin:8px 0 14px;border-radius:9px;padding:9px 12px;font-size:12px;box-shadow:inset 0 0 0 1px ${C.line}"><span class="c1">find</span> /path -maxdepth 1 -name <span class="c2">"*.txt"</span></div><span style="color:${C.t2}">The * matches any characters in the name.</span>
    <div style="display:flex;gap:14px;margin-top:14px;color:${C.mut}">${i('copy', 'width:16px;height:16px')}${i('history', 'width:16px;height:16px')}</div></div></div></div>
  <div style="margin-top:auto;padding:18px 22px"><div style="height:46px;border-radius:23px;background:${C.card2};box-shadow:inset 0 0 0 1px ${C.line};display:flex;align-items:center;padding:0 6px 0 18px;color:${C.mut}">Ask AI<span style="margin-left:auto;width:34px;height:34px;border-radius:50%;background:linear-gradient(180deg,#5CC8FF,#2EA8F0);display:grid;place-items:center;color:#03202E">${i('send', 'width:16px;height:16px')}</span></div></div></div>`
P.termFrame2 = () => P.frame('Terminal', `<div style="display:flex;height:100%"><div class="term" style="flex:1;padding:36px 38px;font-size:13.5px;line-height:1.75;background:#0B0B0E">
  <span class="c5">Last login: Fri Oct 10 08:45:02 2025 from 10.0.0.2</span><br><span class="c2">ira@api-gateway</span>:<span class="c1">~</span>$ uptime<br>&nbsp;08:46:12 up 15 days, 6:02, 3 users, load average: 1.02, 0.88, 0.95<br><br>
  <span class="c2">ira@api-gateway</span>:<span class="c1">~</span>$ df -h /<br>Filesystem&nbsp;&nbsp;&nbsp;Size&nbsp;&nbsp;Used&nbsp;&nbsp;Avail&nbsp;&nbsp;Use%&nbsp;&nbsp;Mounted on<br>/dev/sda1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;80G&nbsp;&nbsp;&nbsp;69G&nbsp;&nbsp;&nbsp;&nbsp;11G&nbsp;&nbsp;&nbsp;<span class="c3">86%</span>&nbsp;&nbsp;/<br><br>
  <span class="c2">ira@api-gateway</span>:<span class="c1">~</span>$ ./check-network-load.sh<br><span class="c4">RX:</span> 1126 KB/s&nbsp;&nbsp;&nbsp;<span class="c4">TX:</span> 1638 KB/s<br><span class="c5"># Logged to ~/.netload.log</span><br><br>
  <span class="c2">ira@api-gateway</span>:<span class="c1">~</span>$ sudo systemctl status nginx<br><span class="c2">●</span> nginx.service - A high performance web server<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Loaded: loaded (/lib/systemd/system/nginx.service; enabled)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Active: <span class="c2">active (running)</span> since Wed 2025-09-24 08:31:10 UTC<br><br>
  <span class="c2">ira@api-gateway</span>:<span class="c1">~</span>$ <span style="display:inline-block;width:9px;height:18px;background:#C4B5FD;vertical-align:-4px"></span></div>${P.termPanel('dock')}</div>`, { tab: 'API Gateway', plus: false })

// ---- sessions: her table, real names, darker ----
const SESS = [['15 Oct 2025', [['Ira Sen', 'ira@platform.dev', '#8B5CF6', 'ubuntu', '10.0.1.12:22', 'MacBook Pro', 'Bengaluru, India', '2h 14m', 'ED25519'], ['Dev Malhotra', 'dev@platform.dev', '#10B981', 'arch', '10.0.1.24:22', 'Android', 'Pune, India', '48m', 'RSA 4096'], ['Sara Thomas', 'sara@platform.dev', '#0EA5E9', 'fedora', '10.0.2.5:22', 'Lenovo 15', 'Kochi, India', '12m', 'ED25519']]], ['14 Oct 2025', [['Arjun Rao', 'arjun@platform.dev', '#F59E0B', 'debian', '10.0.3.18:22', 'Lenovo 15', 'Hyderabad, India', '5h 02m', 'ECDSA'], ['Neha Kulkarni', 'neha@platform.dev', '#EC4899', 'ubuntu', '10.0.0.2:22', 'MacBook Air', 'Mumbai, India', '1h 37m', 'ED25519']]]]
P.sessions2 = () => `<div class="u" style="width:1000px;border-radius:14px;background:#0B0B0E;box-shadow:inset 0 0 0 1px ${C.line};overflow:hidden">
  ${SESS.map(([d, rows], g) => `<div style="display:grid;grid-template-columns:2.3fr 1.6fr 1fr 1.3fr .8fr 1fr 30px;align-items:center;padding:0 26px;height:48px;font-size:13.5px;color:${g ? '#fff' : '#fff'};${g ? `border-top:1px solid ${C.line}` : ''}"><span style="font-weight:500">${d}</span>${g ? '<span></span><span></span><span></span><span></span><span></span><span></span>' : `<span style="color:${C.t2}">OS</span><span style="color:${C.t2}">Device</span><span style="color:${C.t2}">Location</span><span style="color:${C.t2}">Duration</span><span style="color:${C.t2}">Key</span><span></span>`}</div>
   ${rows.map(([n, e, c, o, ip, dev, loc, t, k]) => `<div style="display:grid;grid-template-columns:2.3fr 1.6fr 1fr 1.3fr .8fr 1fr 30px;align-items:center;padding:0 26px;height:72px;border-top:1px solid ${C.line};font-size:14px"><div style="display:flex;align-items:center;gap:14px"><span style="width:42px;height:42px;border-radius:10px;background:${c};display:grid;place-items:center;font-size:17px;font-weight:700;color:#fff">${n[0]}</span><div><div style="display:flex;align-items:center;gap:8px;font-weight:500">${n}<span class="dot" style="background:#34D399;width:7px;height:7px"></span></div><div style="color:${C.t2};font-size:12.5px;margin-top:2px">${e}</div></div></div>
    <div style="display:flex;align-items:center;gap:10px">${os(o).replace('class="os"', 'class="os" style="background:none;box-shadow:none;width:22px;height:22px"')}<span class="mono" style="font-size:13px">${ip}</span></div><span>${dev}</span><span>${loc}</span><span>${t}</span><span style="display:flex;align-items:center;gap:6px;font-size:12.5px">${i('key', 'width:14px;height:14px;color:#38BDF8')}${k}</span><span style="color:${C.t2}">${i('more', 'width:18px;height:18px;transform:rotate(90deg)')}</span></div>`).join('')}`).join('')}</div>`
P.sessionsFrame2 = () => P.frame('Sessions', `<div style="padding:60px 96px 0"><div style="display:flex;align-items:center;gap:14px;margin-bottom:26px"><span style="font-size:24px;font-weight:650">Active Sessions</span><span style="height:30px;padding:0 14px;border-radius:15px;background:rgba(56,189,248,.12);color:#7DD3FC;font-size:12.5px;display:grid;place-items:center">5 active sessions</span></div>${P.sessions2().replace('width:1000px', 'width:100%')}</div>`, { plus: false })
})()
