# python3 scripts/mockups/story-sizes.py: writes src/data/storySizes.ts, the pixel size of every case-study image in
# public/case-studies/*/story/, so the pages can reserve each image's space before it loads.
import glob, os
from PIL import Image
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
rows = []
for p in sorted(glob.glob(os.path.join(root, 'public', 'case-studies', '*', 'story', '*.webp'))):
    w, h = Image.open(p).size
    rows.append(f"  '{os.path.relpath(p, os.path.join(root, 'public')).replace(os.sep, '/')}': [{w}, {h}],")
open(os.path.join(root, 'src', 'data', 'storySizes.ts'), 'w').write(
    '// Generated by scripts/mockups/story-sizes.py: [width, height] of each case-study image in public/.\n'
    'export const STORY_SIZES: Record<string, [number, number]> = {\n' + '\n'.join(rows) + '\n}\n')
print(len(rows))
