// Extra full pages for the hero tiles, built from the Pulsefit library (load after ui.js, site.js).

(function(){
const lib=document.getElementById('lib');
const chk='<svg viewBox="0 0 24 24"><path d="M5 12.500l4.500 4.500L19 7.500"/></svg>';
const MARKW=window.PFMARK('dark');
lib.insertAdjacentHTML('beforeend',`<div id="app-site" class="sx site"><div class="nav"><div class="brand">${MARKW}Pulsefit</div><div class="ln"><span>Home</span><span>About us</span><span>Blog</span><span>Contact</span></div><span class="cta">Join the waitlist</span></div><h1 class="h1">Manage, grow and elevate your fitness business.</h1><p class="p">Pulsefit is all-in-one gym management software. Run leads, members, plans, equipment and staff from one place, and keep every follow-up on time.</p><div class="c1"><span class="cta">Join the waitlist</span></div><div class="row"><span>Leads</span><span>Members</span><span>Plans</span><span>Equipment</span><span>Staff</span></div><div class="panel"><div class="sb"><i class="on" style="width:60%"></i><i></i><i></i><i></i><i></i><i></i></div><div class="tp"></div><div class="k" style="left:140px"><small>New leads</small><b>234</b></div><div class="k" style="left:268px"><small>Demo rate</small><b>23%</b></div><div class="k" style="left:396px;width:104px"><small>Lost</small><b>65</b></div><div class="ch"><svg viewBox="0 0 340 200" style="width:100%;height:100%"><polyline fill="none" stroke="#6AB0FF" stroke-width="3" points="14,150 80,90 150,120 220,60 326,84"/><polyline fill="none" stroke="#F5B400" stroke-width="3" points="14,170 80,140 150,150 220,110 326,126"/></svg></div><div class="tb"><i style="width:80%"></i><i style="width:64%"></i><i style="width:72%"></i><i style="width:55%"></i></div></div></div>`);
// features tabs + copy
lib.insertAdjacentHTML('beforeend',`<div id="c-sitetabs" class="sx" style="width:640px;border-radius:28px;background:#fff;box-shadow:0 0 0 1px #E1E6F1;padding:30px"><div style="display:flex;gap:8px;flex-wrap:wrap">${['Leads and follow-ups','Members','Plans and billing','Equipment','Staff'].map((t,i)=>`<span class="pill${i==0?' on':''}">${t}</span>`).join('')}</div><div style="margin-top:26px;font-family:Poppins;font-weight:600;font-size:26px;line-height:1.25;letter-spacing:-.02em">Follow-ups that turn prospects into members at the right moment.</div><div style="margin-top:22px;display:flex;flex-direction:column;gap:14px">${['Follow-up scheduling','Lead tracking and scoring','Automated trial and tour booking'].map(t=>`<div class="tick"><i>${chk}</i>${t}</div>`).join('')}</div></div>`);
// features flow card
lib.insertAdjacentHTML('beforeend',`<div id="c-sitefeat" class="sx" style="width:545px;height:445px;border-radius:28px;background:linear-gradient(135deg,#EEF5FF,#E8F1FF 60%,#F6FAFF);box-shadow:inset 0 0 0 1px #DCE8F8;position:relative;overflow:hidden">
<svg style="position:absolute;left:0;top:0" width="545" height="445" viewBox="0 0 545 445"><g stroke="#9CC4FF" stroke-width="1.5" fill="none"><path d="M120 74V120"/><path d="M200 232H262"/><path d="M300 232H338"/><path d="M120 340V374"/></g><g fill="#fff" stroke="#9CC4FF" stroke-width="1.5"><circle cx="120" cy="120" r="5"/><circle cx="200" cy="232" r="5"/><circle cx="338" cy="232" r="5"/><circle cx="120" cy="340" r="5"/></g></svg>
<div style="position:absolute;left:62px;top:44px;height:30px;padding:0 12px;border-radius:9px;background:#fff;box-shadow:0 0 0 1px #BBD6FF;font-size:12px;display:flex;align-items:center;gap:6px;font-weight:500">Lead score <b style="color:#003A92">92/100</b></div>
<div style="position:absolute;left:46px;top:120px;width:154px;height:220px;border-radius:20px;background:#fff;box-shadow:0 0 0 1.5px #BBD6FF;padding:16px"><div style="display:flex;align-items:center;gap:8px;font-weight:600;font-size:13px"><span class="av s" style="background:#E4EBFF;color:#0063F8">AM</span>Aarav Mehta</div><div style="display:flex;gap:5px;margin-top:10px"><span class="chip b" style="height:20px;font-size:10px">Trial</span><span class="chip hot" style="height:20px;font-size:10px">Hot</span></div><div style="margin-top:14px;height:44px;border-radius:8px;background:#E8F1FF"></div><div style="margin-top:14px;height:34px;border-radius:9px;background:#0063F8;color:#fff;font-size:11.5px;font-weight:600;display:grid;place-items:center">Convert to member</div></div>
<div style="position:absolute;left:262px;top:212px;width:38px;height:38px;border-radius:50%;background:#0063F8;display:grid;place-items:center"><svg class="i" style="stroke:#fff;width:18px;height:18px"><use href="#i-user-plus"/></svg></div>
<div style="position:absolute;left:338px;top:150px;width:168px;height:170px;border-radius:20px;background:#fff;box-shadow:0 0 0 1.5px #BBD6FF;padding:16px"><div style="font-weight:600;font-size:13px">Assign plan</div><div style="margin-top:12px;height:10px;border-radius:5px;background:#DCE8F8"></div><div style="margin-top:8px;height:10px;width:60%;border-radius:5px;background:#DCE8F8"></div><div style="margin-top:16px;border-radius:10px;background:#EEF5FF;padding:10px"><small style="font-size:10px;color:#7B8196">Total amount</small><div style="font-family:Poppins;font-weight:600;font-size:16px">₹ 3,200</div></div></div>
<div style="position:absolute;left:66px;top:374px;height:30px;padding:0 12px;border-radius:9px;background:#fff;box-shadow:0 0 0 1px #BBD6FF;font-size:12px;display:flex;align-items:center;gap:6px;font-weight:500">Lead growth <b style="color:#0C7A52">+12%</b></div></div>`);
// pricing
const pr=(n,p,hl,items)=>`<div style="width:290px;border-radius:24px;background:#fff;box-shadow:${hl?'0 0 0 2px #0063F8':'0 0 0 1px #E6E8F0'};padding:26px;position:relative">${hl?'<span class="chip b" style="position:absolute;right:20px;top:20px">Most popular</span>':''}<div style="font-family:Poppins;font-weight:600;font-size:18px">${n}</div><div style="margin-top:14px;font-family:Poppins;font-size:40px;font-weight:600;letter-spacing:-.03em">$${p}<small style="font-size:15px;font-weight:400;color:#7B8196;margin-left:4px">/ month</small></div><div style="margin-top:18px;height:44px;border-radius:12px;display:grid;place-items:center;font-weight:600;font-size:14px;${hl?'background:#0063F8;color:#fff':'background:#fff;box-shadow:inset 0 0 0 1.5px #14171F'}">Get started</div><div style="margin-top:22px;display:flex;flex-direction:column;gap:12px">${items.map(t=>`<div class="tick" style="font-size:14px;font-weight:500"><i style="background:#14A06B">${chk}</i>${t}</div>`).join('')}</div></div>`;
lib.insertAdjacentHTML('beforeend',`<div id="c-pricing" class="sx" style="display:flex;gap:20px;width:940px">${pr('Starter',99,0,['Leads and follow-ups','Member records','Plans and billing','Email support'])+pr('Growth',199,1,['Everything in Starter','Attendance insights','Equipment and repairs','Priority support'])+pr('Scale',299,0,['Everything in Growth','Multi-branch reports','Staff management','Dedicated onboarding'])}</div>`);
// FAQ
const fq=(q,a)=>`<div style="border-radius:16px;background:#fff;box-shadow:0 0 0 1px #E6E8F0;padding:18px 22px"><div style="display:flex;align-items:center;justify-content:space-between;font-weight:600;font-size:15px">${q}<svg class="i" style="width:18px;height:18px;color:#7B8196"><use href="#i-chev"/></svg></div>${a?`<div style="margin-top:10px;color:#4B5163;font-size:14px;line-height:1.55">${a}</div>`:''}</div>`;
lib.insertAdjacentHTML('beforeend',`<div id="c-faq" class="sx" style="width:470px;display:flex;flex-direction:column;gap:12px">${fq('How long does it take to get started?','Most gyms are running within 24 hours. We help import your data and set up your account.')+fq('Can I import data from my current system?')+fq('What kind of support do you offer?')+fq('Is there a contract or commitment?')}</div>`);
// how it works
const hw=(i,t,d,body)=>`<div style="width:300px;border-radius:24px;background:#fff;box-shadow:0 0 0 1px #E6E8F0;padding:22px"><div style="height:130px;border-radius:14px;background:#F6F7FB;padding:14px;margin-bottom:18px">${body}</div><div style="display:flex;align-items:center;gap:10px;font-family:Poppins;font-weight:600;font-size:16px"><span style="width:26px;height:26px;border-radius:50%;background:#E6F0FF;color:#0063F8;display:grid;place-items:center;font-size:13px">${i}</span>${t}</div><div style="margin-top:8px;color:#4B5163;font-size:13.5px;line-height:1.55">${d}</div></div>`;
const bar=(w,c)=>`<div style="height:9px;width:${w}%;border-radius:5px;background:${c||'#DDE1F2'};margin-bottom:11px"></div>`;
lib.insertAdjacentHTML('beforeend',`<div id="c-how" class="sx" style="display:flex;gap:18px;width:940px">${hw(1,'Import your data','Bring members, plans and staff across from your spreadsheets.',bar(80,'#0063F8')+bar(62)+bar(72)+bar(48))+hw(2,'Set up your gym','Choose plans, pricing and reminders to match how you run.',bar(55)+bar(85)+bar(40,'#0063F8')+bar(70))+hw(3,'See it add up','Follow leads, attendance and renewals from one dashboard.','<svg viewBox="0 0 250 100" style="width:100%;height:100%"><polyline fill="none" stroke="#0063F8" stroke-width="3" stroke-linecap="round" points="6,84 60,64 110,70 170,30 244,14"/></svg>')}</div>`);
// CTA
lib.insertAdjacentHTML('beforeend',`<div id="c-cta" class="sx" style="width:440px;border-radius:28px;background:radial-gradient(500px 300px at 20% 0%,#0A5BD8,#003A92 60%,#001B4B);padding:34px;color:#fff"><div style="font-family:Poppins;font-weight:600;font-size:25px;line-height:1.2;letter-spacing:-.02em">Ready to stop chasing and start scaling your gym?</div><div style="margin-top:22px"><span class="cta">Schedule a demo</span></div><div style="margin-top:20px;display:flex;gap:20px;font-size:13px;opacity:.85"><span>Set up in 24 hours</span><span>No credit card required</span></div></div>`);
})();


(function(){
const lib=document.getElementById('lib');
// CRM: Create lead (the leads shell with the three-step form).
const a=document.querySelector('#app-leads').cloneNode(true);a.id='app-createlead';
const m=a.querySelector('main.main');
const crumb=m.querySelector('.crumb');crumb.innerHTML='<span>Leads</span><span>/</span><b>Create lead</b>';
const ph=m.querySelector('.ph');ph.querySelector('h1').textContent='Create lead';ph.querySelector('.btn')&&ph.querySelector('.btn').remove();
[...m.children].forEach(c=>{if(c!==crumb&&c!==ph)c.remove()});
const f=document.querySelector('#c-leadform').cloneNode(true);f.removeAttribute('id');f.style.width='100%';m.appendChild(f);
const sub=a.querySelectorAll('.sub > *');sub.forEach((s,i)=>s.classList.toggle('on',s.textContent.trim()==='Create lead'));
lib.appendChild(a);
// Website: pricing page on the site's blue.
const site=document.querySelector('#app-site');
const p=document.createElement('div');p.id='app-pricing';p.className=site.className;p.style.cssText='width:1440px;height:900px;position:relative;overflow:hidden';
p.appendChild(site.querySelector('.nav').cloneNode(true));
const hd=document.createElement('div');hd.style.cssText='text-align:center;color:#fff;margin:150px 0 44px';hd.innerHTML='<div style="font:600 52px/1.1 Poppins,sans-serif;letter-spacing:-.02em">Simple plans for every gym</div><div style="font:400 19px/1.5 Inter,sans-serif;opacity:.8;margin-top:14px">Start with leads and members. Add branches when you grow.</div>';
p.appendChild(hd);
const pr=document.querySelector('#c-pricing').cloneNode(true);pr.removeAttribute('id');pr.style.margin='0 auto';pr.style.zoom='1.18';p.appendChild(pr);
lib.appendChild(p);
})();


(function(){
const lib=document.getElementById('lib');
const f=document.createElement('div');f.id='app-features';f.style.cssText='width:1440px;height:900px;position:relative;overflow:hidden;background:linear-gradient(180deg,#FFFFFF,#EEF4FF);font-family:Inter,sans-serif';
f.innerHTML='<div style="display:flex;align-items:center;gap:40px;padding:30px 72px"><div style="display:flex;align-items:center;gap:10px;font:600 24px Poppins,sans-serif;color:#14171F"><span style="width:26px;height:28px;display:inline-block">'+window.PFMARK('color')+'</span>Pulsefit</div><div style="display:flex;gap:30px;font-size:16px;color:#4A5065;margin-left:60px"><span>Home</span><span style="color:#0063F8;font-weight:600">Features</span><span>Pricing</span><span>Blog</span><span>Contact</span></div><span style="margin-left:auto;background:#0063F8;color:#fff;font-weight:600;font-size:15px;padding:12px 22px;border-radius:10px">Join the waitlist</span></div><div style="text-align:center;margin:26px 0 34px"><div style="font:600 46px/1.1 Poppins,sans-serif;letter-spacing:-.02em;color:#14171F">Everything your front desk does, in one place</div><div style="font-size:18px;color:#5A6075;margin-top:12px">Leads, members, plans, equipment and staff, connected.</div></div><div id="ff-row" style="display:flex;gap:28px;justify-content:center;align-items:flex-start;padding:0 72px"></div>';
lib.appendChild(f);
const row=f.querySelector('#ff-row');
const t=document.querySelector('#c-sitetabs').cloneNode(true);t.removeAttribute('id');t.style.width='640px';
const ft=document.querySelector('#c-sitefeat').cloneNode(true);ft.removeAttribute('id');ft.style.height='420px';ft.style.overflow='hidden';ft.style.borderRadius='24px';
const col=document.createElement('div');col.style.cssText='display:flex;flex-direction:column;gap:24px';col.appendChild(t);const hw=document.querySelector('#c-how').cloneNode(true);hw.removeAttribute('id');hw.style.cssText+=';zoom:.68';col.appendChild(hw);row.appendChild(col);row.appendChild(ft);
})();
